//Maya Preference 2022 (Release 1)
//
//

//
// The hotkey set
//
hotkeySet -source "Maya_Default" -current Maya_Default_Duplicate;
//
// The hotkey contexts and hotkeys
//
hotkey -keyShortcut "F11" -name ("");
hotkey -keyShortcut "q" -sht -name ("SmoothPolygonNameCommand");
hotkey -keyShortcut "q" -sht -releaseName ("");
hotkey -keyShortcut "v" -ctl -sht -name ("Show_ToggleNameCommand");
hotkey -keyShortcut "z" -ctl -sht -name ("SelectHierarchyNameCommand");
hotkey -keyShortcut "v" -ctl -alt -sht -name ("");
hotkey -keyShortcut "c" -ctl -name ("Copy_KeysNameCommand");
hotkey -keyShortcut "2" -alt -name ("SelectEdgeMaskNameCommand");
hotkey -keyShortcut "i" -ctl -name ("ImportNameCommand");
hotkey -keyShortcut "v" -ctl -name ("timeSliderPasteKeyNameCommand");
hotkey -keyShortcut "n" -sht -name ("ReversePolygonNormalsNameCommand");
hotkey -keyShortcut "F6" -name ("GraphEditorNameCommand");
hotkey -keyShortcut "e" -alt -sht -name ("Reset_RNameCommand");
hotkey -keyShortcut "w" -alt -sht -name ("Reset_TNameCommand");
hotkey -keyShortcut "r" -alt -sht -name ("Reset_SNameCommand");
hotkey -keyShortcut "F2" -name ("");
hotkey -keyShortcut "y" -sht -name ("SeparatePolygonNameCommand");
hotkey -keyShortcut "1" -alt -name ("SelectVertexMaskNameCommand");
hotkey -keyShortcut "4" -alt -name ("SelectUVMaskNameCommand");
hotkey -keyShortcut "F4" -name ("TextureViewWindowNameCommand");
hotkey -keyShortcut "x" -alt -name ("dR_objectXrayTGLNameCommand");
hotkey -keyShortcut "!" -name ("FreezeTransformationsNameCommand");
hotkey -keyShortcut "~" -name ("CenterPivotNameCommand");
hotkey -keyShortcut "F3" -name ("");
hotkey -keyShortcut "F12" -name ("HotkeyPreferencesWindowNameCommand");
hotkey -keyShortcut "Return" -name ("");
hotkey -keyShortcut "F9" -name ("");
hotkey -keyShortcut "F10" -name ("");
hotkey -keyShortcut "@" -ctl -name ("");
hotkey -keyShortcut "F5" -name ("HypershadeWindowNameCommand");
hotkey -keyShortcut "r" -ctl -sht -name ("ReferenceEditorNameCommand");
hotkey -keyShortcut "a" -releaseName ("");
hotkey -keyShortcut "3" -alt -name ("SelectFacetMaskNameCommand");
hotkey -keyShortcut "a" -name ("FrameAllNameCommand");
hotkey -keyShortcut "a" -sht -name ("CombinePolygonsNameCommand");
hotkeyCtx -type "Editor" -addClient "hyperShadePanel";
hotkeyCtx -type "Editor" -addClient "graphEditor";
hotkeyCtx -type "Editor" -addClient "polyTexturePlacementPanel";
hotkey -keyShortcut "a" -name ("TogglePolyUVsCreateShaderNameCommand");
hotkeyCtx -type "Editor" -addClient "hyperGraphPanel";
hotkeyCtx -type "Editor" -addClient "profilerPanel";
hotkeyCtx -type "Editor" -addClient "nodeEditorPanel";
hotkeyCtx -type "Editor" -addClient "outlinerPanel";
hotkeyCtx -type "Editor" -addClient "timeEditorPanel";
hotkeyCtx -type "Editor" -addClient "shapePanel";
hotkeyCtx -type "Editor" -addClient "posePanel";
hotkeyCtx -type "Tool" -addClient "xgmIGBrush";
hotkeyCtx -type "Tool" -addClient "Unfold3DBrush";
hotkeyCtx -type "Tool" -addClient "texSculptCacheContext";
hotkeyCtx -type "Tool" -addClient "sculptMeshCache";
hotkeyCtx -type "Tool" -addClient "SymmetrizeUVBrush";
hotkeyCtx -type "Tool" -addClient "polyCutUV";
hotkeyCtx -type "Tool" -addClient "texCutContext";
