# Copyright Epic Games, Inc. All Rights Reserved.
from .version import version, fileformat_version

from .file.reader import RDFReader, read_fileformat_version
from .file.writer import RDFWriter

from .lib import get_rig_definition
from .model.definition import RigDefinition

from .model.common import (
    SectionItem,
    SectionList,
    SectionDict,
)

from .model.items import (
    TranslationUnit,
    RotationUnit,
    Direction,
    CoordinateSystem,
    Descriptor,
    Control,
    ControlMapping,
    Joint,
    JointGroup,
    Region,
    AnimatedMapChannel,
    TextureMask,
    TextureMapType,
    TextureMap,
    ShaderParameter,
    ShaderInput,
    ShaderType,
    Shader,
    Mesh,
    AnimatedMap,
    SplitJoints,
    SplitMap,
    ExpressionType,
    DeformationType,
    MeshDeformer,
    ExpressionFunctionType,
    ExpressionFunction,
    Expression,
    ExpressionMultiplier,
    NoOperationExpressionFunction,
    SplitExpressionFunction,
    SubtractExpressionFunction,
    SumExpressionFunction,
    PhaseExpressionFunction,
    PSDDefinition,
    PSDNet,
    LOD,
    JointWeight,
    MixRegion,
    SymmetrySide,
    SymmetryJoint,
    SymmetryMesh,
    JointAttributeType,
    RBFSolverType,
    RBFFunctionType,
    RBFDistanceMethod,
    RBFPose,
    RBFSolver,
    Twist,
    Swing,
    SkinTransfer,
    SkinTransferMapping,
    ControlType,
    JointAttributeRepresentation,
    RBFInputJoint,
    Face,
    GUIControl,
)


__all__ = [
    # general
    "version",
    "fileformat_version",
    "read_fileformat_version",
    "get_rig_definition",

    # io
    "RDFReader",
    "RDFWriter",

    # model
    "RigDefinition",

    # common
    "SectionItem",
    "SectionList",
    "SectionDict",

    # items
    "TranslationUnit",
    "RotationUnit",
    "Direction",
    "CoordinateSystem",
    "Descriptor",
    "Control",
    "ControlMapping",
    "Joint",
    "JointGroup",
    "Region",
    "AnimatedMapChannel",
    "TextureMask",
    "TextureMapType",
    "TextureMap",
    "ShaderParameter",
    "ShaderInput",
    "ShaderType",
    "Shader",
    "Mesh",
    "AnimatedMap",
    "SplitJoints",
    "SplitMap",
    "ExpressionType",
    "DeformationType",
    "MeshDeformer",
    "ExpressionFunctionType",
    "ExpressionFunction",
    "Expression",
    "ExpressionMultiplier",
    "NoOperationExpressionFunction",
    "SplitExpressionFunction",
    "SubtractExpressionFunction",
    "SumExpressionFunction",
    "PhaseExpressionFunction",
    "PSDDefinition",
    "PSDNet",
    "LOD",
    "JointWeight",
    "MixRegion",
    "SymmetrySide",
    "SymmetryJoint",
    "SymmetryMesh",
    "JointAttributeType",
    "RBFSolverType",
    "RBFFunctionType",
    "RBFDistanceMethod",
    "RBFPose",
    "RBFSolver",
    "Twist",
    "Swing",
    "SkinTransfer",
    "SkinTransferMapping",
    "ControlType",
    "JointAttributeRepresentation",
    "RBFInputJoint",
    "Face",
    "GUIControl"
]
