//Maya Preference 2025 (Release 1)
//
//

optionVar -version 3;

// RecentFiles
optionVar -cat "RecentFiles"
 -sa "RecentFilesList"
 -sva "RecentFilesList" "D:/Justin/MKT/Mem2/CL_Mem2_MKT_Soldier.fbx"
 -sva "RecentFilesList" "D:/Justin/MKT/Mem4/CL_Mem4_MKT_ACC_Headset.fbx"
 -sva "RecentFilesList" "D:/Justin/MKT/Mem5/CL_Mem5_MKT_ACC_Headset.fbx"
 -sva "RecentFilesList" "Z:/OWIS/3D/Rig/CH/Mem2/_Final/FBX/SKM_CH_Mem2_Body.fbx"
 -sva "RecentFilesList" "Z:/OWIS/3D/Rig/CH/Mem3/_Final/FBX/SKM_CH_Mem3_Body.fbx"
 -sva "RecentFilesList" "Z:/OWIS/3D/Rig/CH/Mem4/_Final/FBX/SKM_CH_Mem4_Body.fbx"
 -sva "RecentFilesList" "Z:/OWIS/3D/Rig/CH/Mem5/_Final/FBX/SKM_CH_Mem5_Body.fbx"
 -sva "RecentFilesList" "C:/Users/Justin/Downloads/TEST_D.fbx"
 -sva "RecentFilesList" "Z:/OWIS/3D/Rig/CH_Hair/Mem1/Hair_B/_Final/FBX/SKM_HA_Mem1_Hair_B.fbx"
 -sva "RecentFilesList" "Z:/OWIS/3D/Rig/CL/STA/Mem3/_Final/FBX/SKM_CL_Mem3_STA_Top.fbx"
 -sa "RecentFilesTypeList"
 -sva "RecentFilesTypeList" "FBX"
 -sva "RecentFilesTypeList" "FBX"
 -sva "RecentFilesTypeList" "FBX"
 -sva "RecentFilesTypeList" "FBX"
 -sva "RecentFilesTypeList" "FBX"
 -sva "RecentFilesTypeList" "FBX"
 -sva "RecentFilesTypeList" "FBX"
 -sva "RecentFilesTypeList" "FBX"
 -sva "RecentFilesTypeList" "FBX"
 -sva "RecentFilesTypeList" "FBX"
 -sa "RecentProjectsList"
 -sva "RecentProjectsList" "D:/Justin/CSD/Mem3"
 -sva "RecentProjectsList" "D:/Justin/KDU/Mem1"
 -sva "RecentProjectsList" "D:/Justin/KDU/Mem2"
 -sva "RecentProjectsList" "D:/Justin/KDU/Mem3"
 -sva "RecentProjectsList" "D:/Justin/KDU/Mem5"
 -sva "RecentProjectsList" "D:/Justin/MKT/Mem2"
 -sva "RecentProjectsList" "D:/Justin/MKT/Mem3"
 -sva "RecentProjectsList" "D:/Justin/MKT/Mem4"
 -sva "RecentProjectsList" "D:/Justin/NewFaceModel"
 -sva "RecentProjectsList" "D:/Justin/MKT/Mem1"
 ;

