# Copyright Epic Games, Inc. All Rights Reserved.
# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


import os
if hasattr(os, 'add_dll_directory'):
    for path in os.environ.get('PATH', '').split(';'):
        try:
            if path:
                os.add_dll_directory(path)
        except Exception:
            pass



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")


import os
import sys

module_loader_cls = None
for cls in sys.meta_path:
    if hasattr(cls, '__name__') and cls.__name__ == 'IsolatedModuleLoader':
        module_loader_cls = cls
        break

if module_loader_cls is None:
    import dna
    import rdf
    import _py3dnacalib23_2_4
else:
    dna_rootdir = module_loader_cls.get_module_rootdir('dna') or os.path.dirname(os.path.abspath(__file__))
    dna = module_loader_cls.load_module('dna', rootdir=dna_rootdir)
    rdf_rootdir = module_loader_cls.get_module_rootdir('rdf') or os.path.dirname(os.path.abspath(__file__))
    rdf = module_loader_cls.load_module('rdf', rootdir=rdf_rootdir)
    _py3dnacalib23_2_4 = module_loader_cls.load_module('_py3dnacalib23_2_4', rootdir=os.path.dirname(os.path.abspath(__file__)))


try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def with_metaclass(meta, *bases):
    class metaclass(type):

        def __new__(cls, name, this_bases, d):
            return meta(name, bases, d)

        @classmethod
        def __prepare__(cls, name, this_bases):
            return meta.__prepare__(name, bases)
    return type.__new__(metaclass, 'temporary_class', (), {})

class StatusCode(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    code = property(_py3dnacalib23_2_4.StatusCode_code_get, _py3dnacalib23_2_4.StatusCode_code_set)
    message = property(_py3dnacalib23_2_4.StatusCode_message_get, _py3dnacalib23_2_4.StatusCode_message_set)

    def __init__(self):
        _py3dnacalib23_2_4.StatusCode_swiginit(self, _py3dnacalib23_2_4.new_StatusCode())
    __swig_destroy__ = _py3dnacalib23_2_4.delete_StatusCode

# Register StatusCode in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.StatusCode_swigregister(StatusCode)


def __eq__(lhs, rhs):
    return _py3dnacalib23_2_4.__eq__(lhs, rhs)

def __ne__(lhs, rhs):
    return _py3dnacalib23_2_4.__ne__(lhs, rhs)
class Status(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def isOk():
        return _py3dnacalib23_2_4.Status_isOk()

    @staticmethod
    def get():
        return _py3dnacalib23_2_4.Status_get()

    @staticmethod
    def getHook():
        return _py3dnacalib23_2_4.Status_getHook()

    @staticmethod
    def setHook(hook):
        return _py3dnacalib23_2_4.Status_setHook(hook)

    def __init__(self):
        _py3dnacalib23_2_4.Status_swiginit(self, _py3dnacalib23_2_4.new_Status())
    __swig_destroy__ = _py3dnacalib23_2_4.delete_Status

# Register Status in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.Status_swigregister(Status)

def Status_isOk():
    return _py3dnacalib23_2_4.Status_isOk()

def Status_get():
    return _py3dnacalib23_2_4.Status_get()

def Status_getHook():
    return _py3dnacalib23_2_4.Status_getHook()

def Status_setHook(hook):
    return _py3dnacalib23_2_4.Status_setHook(hook)


if module_loader_cls is not None:
    global_dna = sys.modules.pop('dna', None)
    global_pydna = sys.modules.pop('_py3dna', None)
    local_dna = dna

import dna

if module_loader_cls is not None:
    if '_py3dna' in sys.modules:
        del sys.modules['_py3dna']
    if global_pydna is not None:
        sys.modules['_py3dna'] = global_pydna

    if 'dna' in sys.modules:
        del sys.modules['dna']
    if global_dna is not None:
        sys.modules['dna'] = global_dna

    dna = local_dna


if module_loader_cls is not None:
    global_rdf = sys.modules.pop('rdf', None)
    global_pyrdf = sys.modules.pop('_py3rdf', None)
    local_rdf = rdf

import rdf

if module_loader_cls is not None:
    if '_py3rdf' in sys.modules:
        del sys.modules['_py3rdf']
    if global_pyrdf is not None:
        sys.modules['_py3rdf'] = global_pyrdf

    if 'rdf' in sys.modules:
        del sys.modules['rdf']
    if global_rdf is not None:
        sys.modules['rdf'] = global_rdf

    rdf = local_rdf

class VersionInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def getMajorVersion():
        return _py3dnacalib23_2_4.VersionInfo_getMajorVersion()

    @staticmethod
    def getMinorVersion():
        return _py3dnacalib23_2_4.VersionInfo_getMinorVersion()

    @staticmethod
    def getPatchVersion():
        return _py3dnacalib23_2_4.VersionInfo_getPatchVersion()

    @staticmethod
    def getVersionString():
        return _py3dnacalib23_2_4.VersionInfo_getVersionString()

    @staticmethod
    def getVerboseVersionString():
        return _py3dnacalib23_2_4.VersionInfo_getVerboseVersionString()

    def __init__(self):
        _py3dnacalib23_2_4.VersionInfo_swiginit(self, _py3dnacalib23_2_4.new_VersionInfo())
    __swig_destroy__ = _py3dnacalib23_2_4.delete_VersionInfo

# Register VersionInfo in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.VersionInfo_swigregister(VersionInfo)

def VersionInfo_getMajorVersion():
    return _py3dnacalib23_2_4.VersionInfo_getMajorVersion()

def VersionInfo_getMinorVersion():
    return _py3dnacalib23_2_4.VersionInfo_getMinorVersion()

def VersionInfo_getPatchVersion():
    return _py3dnacalib23_2_4.VersionInfo_getPatchVersion()

def VersionInfo_getVersionString():
    return _py3dnacalib23_2_4.VersionInfo_getVersionString()

def VersionInfo_getVerboseVersionString():
    return _py3dnacalib23_2_4.VersionInfo_getVerboseVersionString()

class DNACalibDNAReader(dna.Reader, dna.Writer):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    @staticmethod
    def create(*args):
        return _py3dnacalib23_2_4.DNACalibDNAReader_create(*args)

    @staticmethod
    def destroy(instance):
        return _py3dnacalib23_2_4.DNACalibDNAReader_destroy(instance)

# Register DNACalibDNAReader in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.DNACalibDNAReader_swigregister(DNACalibDNAReader)

def DNACalibDNAReader_create(*args):
    return _py3dnacalib23_2_4.DNACalibDNAReader_create(*args)

def DNACalibDNAReader_destroy(instance):
    return _py3dnacalib23_2_4.DNACalibDNAReader_destroy(instance)


DNACalibDNAReaderImpl = DNACalibDNAReader

class DNACalibDNAReaderImplReflectionMixin(type):

    def __getattr__(cls, name):
        return getattr(DNACalibDNAReaderImpl, name)

    def __dir__(cls):
        return [name for name in dir(DNACalibDNAReaderImpl) if name not in ("create","destroy")]

class DNACalibDNAReader(with_metaclass(DNACalibDNAReaderImplReflectionMixin, object)):
    __slots__ = ('_args', '_kwargs', '_instance')

    def __init__(self, *args, **kwargs):
        self._args = args
        self._kwargs = kwargs
        self._instance = DNACalibDNAReaderImpl.create(*args, **kwargs)

    def __del__(self):
        DNACalibDNAReaderImpl.destroy(self._instance)

    def _in_slots(self, attr):
        for cls in type(self).__mro__:
            if attr in getattr(cls, '__slots__', []):
                return True
        return False

    def __getattr__(self, attr):
        if self._in_slots(attr):
            return object.__getattr__(self, attr)
        return getattr(self._instance, attr)

    def __setattr__(self, attr, value):
        if self._in_slots(attr):
            object.__setattr__(self, attr, value)
        else:
            setattr(self._instance, attr, value)

    def __dir__(self):
        return [name for name in self._instance.__dir__() if name not in ("create","destroy")]

class Command(object):
    r"""    Command is an abstract class whose implementations are expected to modify the DNA provided in the run() method in some way."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_Command

    def run(self, output):
        return _py3dnacalib23_2_4.Command_run(self, output)

# Register Command in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.Command_swigregister(Command)

VectorOperation_Interpolate = _py3dnacalib23_2_4.VectorOperation_Interpolate
VectorOperation_Add = _py3dnacalib23_2_4.VectorOperation_Add
VectorOperation_Subtract = _py3dnacalib23_2_4.VectorOperation_Subtract
VectorOperation_Multiply = _py3dnacalib23_2_4.VectorOperation_Multiply
class CommandSequence(Command):
    r"""
    CommandSequence is used to run a sequence of commands on the same DNA.
    Notes: 
        Commands will be run in the order in which they were added to the sequence.

        CommandSequence holds pointers to commands, but does not own them.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_CommandSequence

    def __init__(self, *args):
        _py3dnacalib23_2_4.CommandSequence_swiginit(self, _py3dnacalib23_2_4.new_CommandSequence(*args))

    def run(self, output):
        return _py3dnacalib23_2_4.CommandSequence_run(self, output)

    def add(self, command):
        r"""
        Method for adding a command to a sequence of commands to run.
        :type command: :py:class:`Command`
        :param command:
                The command to add.
        """
        return _py3dnacalib23_2_4.CommandSequence_add(self, command)

    def remove(self, command):
        r"""
        Method for removing a command from the sequence of commands to run.
        :type command: :py:class:`Command`
        :param command:
                The command to remove.
        """
        return _py3dnacalib23_2_4.CommandSequence_remove(self, command)

    def contains(self, command):
        r"""
        Method for checking if the provided command is part of the command sequence.
        :type command: :py:class:`Command`
        :param command:
                The command to check.
        """
        return _py3dnacalib23_2_4.CommandSequence_contains(self, command)

    def size(self):
        r"""            Number of commands in command sequence."""
        return _py3dnacalib23_2_4.CommandSequence_size(self)

# Register CommandSequence in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.CommandSequence_swigregister(CommandSequence)


def arg_preserver_init(_init):
    def wrapper(self, *args, **kwargs):
        self._args = args
        self._kwargs = kwargs
        _init(self, *args, **kwargs)
    return wrapper

def command_sequence_init(_init):
    preserver = arg_preserver_init(_init)
    def wrapper(self, *args, **kwargs):
        self._commands = []
        preserver(self, *args, **kwargs)
    return wrapper

def command_sequence_add(_add):
    def wrapper(self, command):
        self._commands.append(command)
        _add(self, command)
    return wrapper

def command_sequence_remove(_remove):
    def wrapper(self, command):
        self._commands.remove(command)
        _remove(self, command)
    return wrapper

CommandSequence.__init__ = command_sequence_init(CommandSequence.__init__)
CommandSequence.add = command_sequence_add(CommandSequence.add)
CommandSequence.remove = command_sequence_remove(CommandSequence.remove)

class CalculateMeshLowerLODsCommand(Command):
    r"""
    CalculateMeshLowerLODsCommand is used to recalculate vertex positions for lower LOD meshes of the specified mesh.
    Notes: 
        The calculation is done based on vertex positions of the specified mesh and vertex texture coordinates of its lower LOD meshes.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_CalculateMeshLowerLODsCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.CalculateMeshLowerLODsCommand_swiginit(self, _py3dnacalib23_2_4.new_CalculateMeshLowerLODsCommand(*args))

    def setMeshIndex(self, meshIndex):
        r"""
        Method for setting the index of the mesh to calculate lower LOD meshes from.
        :type meshIndex: int
        :param meshIndex:
                The index of the mesh.
        """
        return _py3dnacalib23_2_4.CalculateMeshLowerLODsCommand_setMeshIndex(self, meshIndex)

    def run(self, output):
        return _py3dnacalib23_2_4.CalculateMeshLowerLODsCommand_run(self, output)

# Register CalculateMeshLowerLODsCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.CalculateMeshLowerLODsCommand_swigregister(CalculateMeshLowerLODsCommand)

class ClearBlendShapesCommand(Command):
    r"""
    ClearBlendShapesCommand is used to clear all blend shapes data from a DNA.
    Notes: This command clears blend shape target deltas and blend shape animation data. By doing so, it transforms the DNA to be "joints only".
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_ClearBlendShapesCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.ClearBlendShapesCommand_swiginit(self, _py3dnacalib23_2_4.new_ClearBlendShapesCommand(*args))

    def run(self, output):
        return _py3dnacalib23_2_4.ClearBlendShapesCommand_run(self, output)

# Register ClearBlendShapesCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.ClearBlendShapesCommand_swigregister(ClearBlendShapesCommand)

class ConvertUnitsCommand(Command):
    r"""    ConvertUnitsCommand is used to perform unit conversions over all relevant data in a DNA."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_ConvertUnitsCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.ConvertUnitsCommand_swiginit(self, _py3dnacalib23_2_4.new_ConvertUnitsCommand(*args))

    def setTranslationUnit(self, translationUnit):
        return _py3dnacalib23_2_4.ConvertUnitsCommand_setTranslationUnit(self, translationUnit)

    def setRotationUnit(self, rotationUnit):
        return _py3dnacalib23_2_4.ConvertUnitsCommand_setRotationUnit(self, rotationUnit)

    def run(self, output):
        return _py3dnacalib23_2_4.ConvertUnitsCommand_run(self, output)

# Register ConvertUnitsCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.ConvertUnitsCommand_swigregister(ConvertUnitsCommand)

class PruneBlendShapeTargetsCommand(Command):
    r"""    PruneBlendShapeTargetsCommand is used to prune blend shape target deltas whose absolute magnitude is less than or equal to the specified threshold."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_PruneBlendShapeTargetsCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.PruneBlendShapeTargetsCommand_swiginit(self, _py3dnacalib23_2_4.new_PruneBlendShapeTargetsCommand(*args))

    def setThreshold(self, threshold):
        r"""
        Method for setting the threshold for pruning blend shape target deltas.
        :type threshold: float
        :param threshold:
                The threshold to use.
        """
        return _py3dnacalib23_2_4.PruneBlendShapeTargetsCommand_setThreshold(self, threshold)

    def run(self, output):
        return _py3dnacalib23_2_4.PruneBlendShapeTargetsCommand_run(self, output)

# Register PruneBlendShapeTargetsCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.PruneBlendShapeTargetsCommand_swigregister(PruneBlendShapeTargetsCommand)

class RemoveAnimatedMapCommand(Command):
    r"""    RemoveAnimatedMapCommand is used to remove animated maps."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_RemoveAnimatedMapCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.RemoveAnimatedMapCommand_swiginit(self, _py3dnacalib23_2_4.new_RemoveAnimatedMapCommand(*args))

    def setAnimatedMapIndex(self, animatedMapIndex):
        r"""
        Method for setting the index of the animated map to remove.
        :type animatedMapIndex: int
        :param animatedMapIndex:
                The index of the animated map.
        Notes: Call to either setter overwrites previous setter calls. When running the command, the last set animated map(s) will be removed.
        """
        return _py3dnacalib23_2_4.RemoveAnimatedMapCommand_setAnimatedMapIndex(self, animatedMapIndex)

    def setAnimatedMapIndices(self, animatedMapIndices):
        r"""
        Method for setting the indices of animated maps to remove.
        :type animatedMapIndices: dnac2::ConstArrayView< std::uint16_t >
        :param animatedMapIndices:
                The animated map indices.
        Notes: Call to either setter overwrites previous setter calls. When running the command, the last set animated map(s) will be removed.
        """
        return _py3dnacalib23_2_4.RemoveAnimatedMapCommand_setAnimatedMapIndices(self, animatedMapIndices)

    def run(self, output):
        return _py3dnacalib23_2_4.RemoveAnimatedMapCommand_run(self, output)

# Register RemoveAnimatedMapCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.RemoveAnimatedMapCommand_swigregister(RemoveAnimatedMapCommand)

class RemoveBlendShapeCommand(Command):
    r"""    RemoveBlendShapeCommand is used to remove blend shapes."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_RemoveBlendShapeCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.RemoveBlendShapeCommand_swiginit(self, _py3dnacalib23_2_4.new_RemoveBlendShapeCommand(*args))

    def setBlendShapeIndex(self, blendShapeIndex):
        r"""
        Method for setting the index of the blend shape to remove.
        :type blendShapeIndex: int
        :param blendShapeIndex:
                The index of the blend shape.
        Notes: Call to either setter overwrites previous setter calls. When running the command, the last set blend shape(s) will be removed.
        """
        return _py3dnacalib23_2_4.RemoveBlendShapeCommand_setBlendShapeIndex(self, blendShapeIndex)

    def setBlendShapeIndices(self, blendShapeIndices):
        r"""
        Method for setting the indices of blend shapes to remove.
        :type blendShapeIndices: dnac2::ConstArrayView< std::uint16_t >
        :param blendShapeIndices:
                The blend shape indices.
        Notes: Call to either setter overwrites previous setter calls. When running the command, the last set blend shape(s) will be removed.
        """
        return _py3dnacalib23_2_4.RemoveBlendShapeCommand_setBlendShapeIndices(self, blendShapeIndices)

    def run(self, output):
        return _py3dnacalib23_2_4.RemoveBlendShapeCommand_run(self, output)

# Register RemoveBlendShapeCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.RemoveBlendShapeCommand_swigregister(RemoveBlendShapeCommand)

class RemoveJointAnimationCommand(Command):
    r"""    RemoveJointAnimationCommand is used to remove joint animation data."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_RemoveJointAnimationCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.RemoveJointAnimationCommand_swiginit(self, _py3dnacalib23_2_4.new_RemoveJointAnimationCommand(*args))

    def setJointIndex(self, jointIndex):
        r"""
        Method for setting the index of a joint whose animation data to remove.
        :type jointIndex: int
        :param jointIndex:
                The index of the joint.
        Notes: Call to either setter overwrites previous setter calls. When running the command, the last set joint animation(s) will be removed.
        """
        return _py3dnacalib23_2_4.RemoveJointAnimationCommand_setJointIndex(self, jointIndex)

    def setJointIndices(self, jointIndices):
        r"""
        Method for setting the indices of joints whose animation data to remove.
        :type jointIndices: dnac2::ConstArrayView< std::uint16_t >
        :param jointIndices:
                The joint indices.
        Notes: Call to either setter overwrites previous setter calls. When running the command, the last set joint animation(s) will be removed.
        """
        return _py3dnacalib23_2_4.RemoveJointAnimationCommand_setJointIndices(self, jointIndices)

    def run(self, output):
        return _py3dnacalib23_2_4.RemoveJointAnimationCommand_run(self, output)

# Register RemoveJointAnimationCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.RemoveJointAnimationCommand_swigregister(RemoveJointAnimationCommand)

class RemoveJointCommand(Command):
    r"""    RemoveJointCommand is used to remove joints."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_RemoveJointCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.RemoveJointCommand_swiginit(self, _py3dnacalib23_2_4.new_RemoveJointCommand(*args))

    def setJointIndex(self, jointIndex):
        r"""
        Method for setting the index of the joint to remove.
        :type jointIndex: int
        :param jointIndex:
                The index of the joint.
        Notes: Call to either setter overwrites previous setter calls. When running the command, the last set joint(s) will be removed.
        """
        return _py3dnacalib23_2_4.RemoveJointCommand_setJointIndex(self, jointIndex)

    def setJointIndices(self, jointIndices):
        r"""
        Method for setting the indices of joints to remove.
        :type jointIndices: dnac2::ConstArrayView< std::uint16_t >
        :param jointIndices:
                The joint indices.
        Notes: Call to either setter overwrites previous setter calls. When running the command, the last set joint(s) will be removed.
        """
        return _py3dnacalib23_2_4.RemoveJointCommand_setJointIndices(self, jointIndices)

    def run(self, output):
        return _py3dnacalib23_2_4.RemoveJointCommand_run(self, output)

# Register RemoveJointCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.RemoveJointCommand_swigregister(RemoveJointCommand)

class RemoveMeshCommand(Command):
    r"""    RemoveMeshCommand is used to remove meshes."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_RemoveMeshCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.RemoveMeshCommand_swiginit(self, _py3dnacalib23_2_4.new_RemoveMeshCommand(*args))

    def setMeshIndex(self, meshIndex):
        r"""
        Method for setting the index of the mesh to remove.
        :type meshIndex: int
        :param meshIndex:
                The index of the mesh.
        """
        return _py3dnacalib23_2_4.RemoveMeshCommand_setMeshIndex(self, meshIndex)

    def setMeshIndices(self, meshIndices):
        r"""
        Method for setting the indices of meshes to remove.
        :type meshIndices: dnac2::ConstArrayView< std::uint16_t >
        :param meshIndices:
                The mesh indices.
        Notes: Call to either setter overwrites previous setter calls. When running the command, the last set mesh(es) will be removed.
        """
        return _py3dnacalib23_2_4.RemoveMeshCommand_setMeshIndices(self, meshIndices)

    def run(self, output):
        return _py3dnacalib23_2_4.RemoveMeshCommand_run(self, output)

# Register RemoveMeshCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.RemoveMeshCommand_swigregister(RemoveMeshCommand)

class RenameAnimatedMapCommand(Command):
    r"""    RenameAnimatedMapCommand is used to rename an animated map."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_RenameAnimatedMapCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.RenameAnimatedMapCommand_swiginit(self, _py3dnacalib23_2_4.new_RenameAnimatedMapCommand(*args))

    def setName(self, *args):
        r"""
        *Overload 1:*

        Method for setting a new name for animated map with given index.
        :type animatedMapIndex: int
        :param animatedMapIndex:
                The index of the animated map whose name to change.
        :type newName: string
        :param newName:
                The new name for the animated map.

        |

        *Overload 2:*

        Method for setting a new name for animated map with given name.
        Notes: 
            The renaming will not happen if there is no animated map with given current name.
        :type oldName: string
        :param oldName:
                The current name of the animated map whose name to change.
        :type newName: string
        :param newName:
                The new name for the animated map.
        """
        return _py3dnacalib23_2_4.RenameAnimatedMapCommand_setName(self, *args)

    def run(self, output):
        return _py3dnacalib23_2_4.RenameAnimatedMapCommand_run(self, output)

# Register RenameAnimatedMapCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.RenameAnimatedMapCommand_swigregister(RenameAnimatedMapCommand)

class RenameBlendShapeCommand(Command):
    r"""    RenameBlendShapeCommand is used to rename a blend shape channel."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_RenameBlendShapeCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.RenameBlendShapeCommand_swiginit(self, _py3dnacalib23_2_4.new_RenameBlendShapeCommand(*args))

    def setName(self, *args):
        r"""
        *Overload 1:*

        Method for setting a new name for blend shape channel with given index.
        :type blendShapeIndex: int
        :param blendShapeIndex:
                The index of the blend shape channel whose name to change.
        :type newName: string
        :param newName:
                The new name for the blend shape channel.

        |

        *Overload 2:*

        Method for setting a new name for blend shape channel with given name.
        Notes: 
            The renaming will not happen if there is no blend shape channel with given current name.
        :type oldName: string
        :param oldName:
                The current name of the blend shape channel whose name to change.
        :type newName: string
        :param newName:
                The new name for the blend shape channel.
        """
        return _py3dnacalib23_2_4.RenameBlendShapeCommand_setName(self, *args)

    def run(self, output):
        return _py3dnacalib23_2_4.RenameBlendShapeCommand_run(self, output)

# Register RenameBlendShapeCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.RenameBlendShapeCommand_swigregister(RenameBlendShapeCommand)

class RenameJointCommand(Command):
    r"""    RenameJointCommand is used to rename a joint."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_RenameJointCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.RenameJointCommand_swiginit(self, _py3dnacalib23_2_4.new_RenameJointCommand(*args))

    def setName(self, *args):
        r"""
        *Overload 1:*

        Method for setting a new name for joint with given index.
        :type jointIndex: int
        :param jointIndex:
                The index of the joint whose name to change.
        :type newName: string
        :param newName:
                The new name for the joint.

        |

        *Overload 2:*

        Method for setting a new name for joint with given name.
        Notes: 
            The renaming will not happen if there is no joint with given current name.
        :type oldName: string
        :param oldName:
                The current name of the joint whose name to change.
        :type newName: string
        :param newName:
                The new name for the joint.
        """
        return _py3dnacalib23_2_4.RenameJointCommand_setName(self, *args)

    def run(self, output):
        return _py3dnacalib23_2_4.RenameJointCommand_run(self, output)

# Register RenameJointCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.RenameJointCommand_swigregister(RenameJointCommand)

class RenameMeshCommand(Command):
    r"""    RenameMeshCommand is used to rename a mesh."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_RenameMeshCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.RenameMeshCommand_swiginit(self, _py3dnacalib23_2_4.new_RenameMeshCommand(*args))

    def setName(self, *args):
        r"""
        *Overload 1:*

        Method for setting a new name for mesh with given index.
        :type meshIndex: int
        :param meshIndex:
                The index of the mesh whose name to change.
        :type newName: string
        :param newName:
                The new name for the mesh.

        |

        *Overload 2:*

        Method for setting a new name for mesh with given name.
        Notes: 
            The renaming will not happen if there is no mesh with given current name.
        :type oldName: string
        :param oldName:
                The current name of the mesh whose name to change.
        :type newName: string
        :param newName:
                The new name for the mesh.
        """
        return _py3dnacalib23_2_4.RenameMeshCommand_setName(self, *args)

    def run(self, output):
        return _py3dnacalib23_2_4.RenameMeshCommand_run(self, output)

# Register RenameMeshCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.RenameMeshCommand_swigregister(RenameMeshCommand)

class RotateCommand(Command):
    r"""
    RotateCommand is used to rotate neutral joints and vertex positions around given origin.
    Notes: 
        Joint rotations are represented in parent space, so it is enough to rotate only root joints, as that rotation will be propagated to the rest of the joints.

        If the origin is not set, the assumed origin is (0, 0, 0).
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_RotateCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.RotateCommand_swiginit(self, _py3dnacalib23_2_4.new_RotateCommand(*args))

    def setRotation(self, degrees):
        r"""
        Method for setting the rotation angles.
        :type degrees: dnac2::Vector3
        :param degrees:
                Rotation angles in degrees.
        """
        return _py3dnacalib23_2_4.RotateCommand_setRotation(self, degrees)

    def setOrigin(self, origin):
        r"""
        Method for setting the rotation origin.
        :type origin: dnac2::Vector3
        :param origin:
                Origin coordinates.
        """
        return _py3dnacalib23_2_4.RotateCommand_setOrigin(self, origin)

    def run(self, output):
        return _py3dnacalib23_2_4.RotateCommand_run(self, output)

# Register RotateCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.RotateCommand_swigregister(RotateCommand)

class ScaleCommand(Command):
    r"""
    ScaleCommand is used to scale neutral joints, vertex positions and joint and blendshape deltas by a factor.
    Notes: 
        Only translation attributes of neutral joints and joint deltas are scaled.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_ScaleCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.ScaleCommand_swiginit(self, _py3dnacalib23_2_4.new_ScaleCommand(*args))

    def setScale(self, scale):
        r"""
        Method for setting the scale factor to multiply with.
        :type scale: float
        :param scale:
                Scale factor.
        """
        return _py3dnacalib23_2_4.ScaleCommand_setScale(self, scale)

    def setOrigin(self, origin):
        r"""
        Method for setting the origin.
        Notes: The origin is used to properly scale position values (vertex positions and neutral joint translations).
        :type origin: dnac2::Vector3
        :param origin:
                Origin coordinates.
        """
        return _py3dnacalib23_2_4.ScaleCommand_setOrigin(self, origin)

    def run(self, output):
        return _py3dnacalib23_2_4.ScaleCommand_run(self, output)

# Register ScaleCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.ScaleCommand_swigregister(ScaleCommand)

class SetBlendShapeTargetDeltasCommand(Command):
    r"""    SetBlendShapeTargetDeltasCommand is used to change blend shape target deltas."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_SetBlendShapeTargetDeltasCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.SetBlendShapeTargetDeltasCommand_swiginit(self, _py3dnacalib23_2_4.new_SetBlendShapeTargetDeltasCommand(*args))

    def setMeshIndex(self, meshIndex):
        r"""
        Method for setting the index of the mesh whose blend shape target to change.
        :type meshIndex: int
        :param meshIndex:
                The mesh index.
        """
        return _py3dnacalib23_2_4.SetBlendShapeTargetDeltasCommand_setMeshIndex(self, meshIndex)

    def setBlendShapeTargetIndex(self, blendShapeTargetIndex):
        r"""
        Method for setting the index of the blend shape target to change.
        :type blendShapeTargetIndex: int
        :param blendShapeTargetIndex:
                The blend shape target index.
        """
        return _py3dnacalib23_2_4.SetBlendShapeTargetDeltasCommand_setBlendShapeTargetIndex(self, blendShapeTargetIndex)

    def setDeltas(self, *args):
        r"""
        *Overload 1:*

        Method for setting the values used to calculate new deltas for blend shape target.
        :type deltas: dnac2::ConstArrayView< dnac2::Vector3 >
        :param deltas:
                The values used in calculation.

        |

        *Overload 2:*

        Method for setting the values used to calculate new deltas for blend shape target.
        :type xs: dnac2::ConstArrayView< float >
        :param xs:
                The X values for each delta.
        :type ys: dnac2::ConstArrayView< float >
        :param ys:
                The Y values for each delta.
        :type zs: dnac2::ConstArrayView< float >
        :param zs:
                The Z values for each delta.
        """
        return _py3dnacalib23_2_4.SetBlendShapeTargetDeltasCommand_setDeltas(self, *args)

    def setVertexIndices(self, vertexIndices):
        r"""
        Method for setting the vertex indices that correspond to new deltas.
        :type vertexIndices: dnac2::ConstArrayView< std::uint32_t >
        :param vertexIndices:
                The vertexIndices.
        """
        return _py3dnacalib23_2_4.SetBlendShapeTargetDeltasCommand_setVertexIndices(self, vertexIndices)

    def setMasks(self, masks):
        r"""
        Method for setting masks used to calculate new deltas for blend shape target.
        Notes: 
            If no masks are set, default weight value of 1 is used for each delta.
        :type masks: dnac2::ConstArrayView< float >
        :param masks:
                The weights for each delta.
        """
        return _py3dnacalib23_2_4.SetBlendShapeTargetDeltasCommand_setMasks(self, masks)

    def setOperation(self, operation):
        r"""
        Method for setting the type of operation used to calculate new deltas for blend shape target.
        Notes: 
            Available operations are: Interpolate, Add, Subtract and Multiply. Each delta is calculated based on the provided operation type in the following way:

            Interpolate: = previousValue * (1 - weight) + setValue * weight:math:`\n                Add: \f$newValue = previousValue + (setValue * weight)`

            Subtract: = previousValue - (setValue * weight):math:`\n                Multiply: \f$newValue = previousValue * (setValue * weight)`


            setValue is the value from new deltas that were set, and weight is the value from masks array.
        :type operation: int
        :param operation:
                The operation to use.
        """
        return _py3dnacalib23_2_4.SetBlendShapeTargetDeltasCommand_setOperation(self, operation)

    def run(self, output):
        return _py3dnacalib23_2_4.SetBlendShapeTargetDeltasCommand_run(self, output)

# Register SetBlendShapeTargetDeltasCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.SetBlendShapeTargetDeltasCommand_swigregister(SetBlendShapeTargetDeltasCommand)
cvar = _py3dnacalib23_2_4.cvar
SetBlendShapeTargetDeltasCommand.VertexIndicesOutOfBoundsError = _py3dnacalib23_2_4.cvar.SetBlendShapeTargetDeltasCommand_VertexIndicesOutOfBoundsError
SetBlendShapeTargetDeltasCommand.NoVertexIndicesSetError = _py3dnacalib23_2_4.cvar.SetBlendShapeTargetDeltasCommand_NoVertexIndicesSetError
SetBlendShapeTargetDeltasCommand.DeltasVertexIndicesCountMismatch = _py3dnacalib23_2_4.cvar.SetBlendShapeTargetDeltasCommand_DeltasVertexIndicesCountMismatch
SetBlendShapeTargetDeltasCommand.DeltasMasksCountMismatch = _py3dnacalib23_2_4.cvar.SetBlendShapeTargetDeltasCommand_DeltasMasksCountMismatch

class SetLODsCommand(Command):
    r"""    SetLODsCommand is used to specify LODs to use. Joints, blend shapes, animated maps and meshes that are not in specified LODs are removed from the DNA."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_SetLODsCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.SetLODsCommand_swiginit(self, _py3dnacalib23_2_4.new_SetLODsCommand(*args))

    def setLODs(self, lods):
        r"""
        Method for setting the LODs to keep.
        :type lods: dnac2::ConstArrayView< std::uint16_t >
        :param lods:
                New LODs to be used.
        """
        return _py3dnacalib23_2_4.SetLODsCommand_setLODs(self, lods)

    def run(self, output):
        return _py3dnacalib23_2_4.SetLODsCommand_run(self, output)

# Register SetLODsCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.SetLODsCommand_swigregister(SetLODsCommand)

class SetNeutralJointRotationsCommand(Command):
    r"""    SetNeutralJointRotationsCommand is used to set new rotation values to neutral joints."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_SetNeutralJointRotationsCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.SetNeutralJointRotationsCommand_swiginit(self, _py3dnacalib23_2_4.new_SetNeutralJointRotationsCommand(*args))

    def setRotations(self, *args):
        r"""
        *Overload 1:*

        Method for setting the neutral joint rotations.
        :type rotations: dnac2::ConstArrayView< dnac2::Vector3 >
        :param rotations:
                Rotation values for each joint.

        |

        *Overload 2:*

        Method for setting the neutral joint rotations.
        :type xs: dnac2::ConstArrayView< float >
        :param xs:
                The X rotation value for each joint.
        :type ys: dnac2::ConstArrayView< float >
        :param ys:
                The Y rotation value for each joint.
        :type zs: dnac2::ConstArrayView< float >
        :param zs:
                The Z rotation value for each joint.
        """
        return _py3dnacalib23_2_4.SetNeutralJointRotationsCommand_setRotations(self, *args)

    def run(self, output):
        return _py3dnacalib23_2_4.SetNeutralJointRotationsCommand_run(self, output)

# Register SetNeutralJointRotationsCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.SetNeutralJointRotationsCommand_swigregister(SetNeutralJointRotationsCommand)

class SetNeutralJointTranslationsCommand(Command):
    r"""    SetNeutralJointTranslationsCommand is used to set new translation values to neutral joints."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_SetNeutralJointTranslationsCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.SetNeutralJointTranslationsCommand_swiginit(self, _py3dnacalib23_2_4.new_SetNeutralJointTranslationsCommand(*args))

    def setTranslations(self, *args):
        r"""
        *Overload 1:*

        Method for setting the neutral joint translations.
        :type translations: dnac2::ConstArrayView< dnac2::Vector3 >
        :param translations:
                Translation values for each joint.

        |

        *Overload 2:*

        Method for setting the neutral joint translations.
        :type xs: dnac2::ConstArrayView< float >
        :param xs:
                The X translation value for each joint.
        :type ys: dnac2::ConstArrayView< float >
        :param ys:
                The Y translation value for each joint.
        :type zs: dnac2::ConstArrayView< float >
        :param zs:
                The Z translation value for each joint.
        """
        return _py3dnacalib23_2_4.SetNeutralJointTranslationsCommand_setTranslations(self, *args)

    def run(self, output):
        return _py3dnacalib23_2_4.SetNeutralJointTranslationsCommand_run(self, output)

# Register SetNeutralJointTranslationsCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.SetNeutralJointTranslationsCommand_swigregister(SetNeutralJointTranslationsCommand)

class SetSkinWeightsCommand(Command):
    r"""    SetSkinWeightsCommand is used to set new skin weights for a vertex in a mesh."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_SetSkinWeightsCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.SetSkinWeightsCommand_swiginit(self, _py3dnacalib23_2_4.new_SetSkinWeightsCommand(*args))

    def setMeshIndex(self, meshIndex):
        r"""
        Method for setting the index of the targeted mesh.
        :type meshIndex: int
        :param meshIndex:
                The mesh index.
        """
        return _py3dnacalib23_2_4.SetSkinWeightsCommand_setMeshIndex(self, meshIndex)

    def setVertexIndex(self, vertexIndex):
        r"""
        Method for setting the index of the vertex to change.
        :type vertexIndex: int
        :param vertexIndex:
                The vertex index.
        """
        return _py3dnacalib23_2_4.SetSkinWeightsCommand_setVertexIndex(self, vertexIndex)

    def setWeights(self, weights):
        r"""
        Method for setting the weights with which joints influence the vertex in question.
        :type weights: dnac2::ConstArrayView< float >
        :param weights:
                Weights for each joint that has an influence on the vertex.
        """
        return _py3dnacalib23_2_4.SetSkinWeightsCommand_setWeights(self, weights)

    def setJointIndices(self, jointIndices):
        r"""
        Method for setting the joint indices of joints that influence the vertex in question.
        :type jointIndices: dnac2::ConstArrayView< std::uint16_t >
        :param jointIndices:
                Joint indices of joints that have an influence on the vertex.
        """
        return _py3dnacalib23_2_4.SetSkinWeightsCommand_setJointIndices(self, jointIndices)

    def run(self, output):
        return _py3dnacalib23_2_4.SetSkinWeightsCommand_run(self, output)

# Register SetSkinWeightsCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.SetSkinWeightsCommand_swigregister(SetSkinWeightsCommand)

class SetVertexPositionsCommand(Command):
    r"""    SetVertexPositionsCommand is used to change vertex positions values."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_SetVertexPositionsCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.SetVertexPositionsCommand_swiginit(self, _py3dnacalib23_2_4.new_SetVertexPositionsCommand(*args))

    def setMeshIndex(self, meshIndex):
        r"""
        Method for setting the index of the mesh to change.
        :type meshIndex: int
        :param meshIndex:
                The mesh index.
        """
        return _py3dnacalib23_2_4.SetVertexPositionsCommand_setMeshIndex(self, meshIndex)

    def setPositions(self, *args):
        r"""
        *Overload 1:*

        Method for setting the vertex positions used to calculate new values.
        :type positions: dnac2::ConstArrayView< dnac2::Vector3 >
        :param positions:
                The vertex positions.

        |

        *Overload 2:*

        Method for setting the vertex positions used to calculate new values.
        :type xs: dnac2::ConstArrayView< float >
        :param xs:
                The X coordinates for each vertex.
        :type ys: dnac2::ConstArrayView< float >
        :param ys:
                The Y coordinates for each vertex.
        :type zs: dnac2::ConstArrayView< float >
        :param zs:
                The Z coordinates for each vertex.
        """
        return _py3dnacalib23_2_4.SetVertexPositionsCommand_setPositions(self, *args)

    def setMasks(self, masks):
        r"""
        Method for setting vertex masks used to calculate new vertex position values.
        Notes: 
            If no masks are set, default weight value of 1 is used for each vertex.
        :type masks: dnac2::ConstArrayView< float >
        :param masks:
                The weights for each vertex.
        """
        return _py3dnacalib23_2_4.SetVertexPositionsCommand_setMasks(self, masks)

    def setOperation(self, operation):
        r"""
        Method for setting the type of operation used to calculate new vertex position values.
        Notes: 
            Available operations are: Interpolate, Add, Subtract and Multiply. Each position is calculated based on the provided operation type in the following way:

            Interpolate: = previousValue * (1 - weight) + setValue * weight:math:`\n                Add: \f$newValue = previousValue + (setValue * weight)`

            Subtract: = previousValue - (setValue * weight):math:`\n                Multiply: \f$newValue = previousValue * (setValue * weight)`


            setValue is the value from new positions that were set, and weight is the value from masks array.
        :type operation: int
        :param operation:
                The operation to use.
        """
        return _py3dnacalib23_2_4.SetVertexPositionsCommand_setOperation(self, operation)

    def run(self, output):
        return _py3dnacalib23_2_4.SetVertexPositionsCommand_run(self, output)

# Register SetVertexPositionsCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.SetVertexPositionsCommand_swigregister(SetVertexPositionsCommand)
SetVertexPositionsCommand.PositionsMasksCountMismatch = _py3dnacalib23_2_4.cvar.SetVertexPositionsCommand_PositionsMasksCountMismatch

class TranslateCommand(Command):
    r"""
    TranslateCommand is used to translate neutral joints and vertex positions.
    Notes: 
        Joint translations are represented in parent space, so it is enough to translate only root joints, as that translation will be propagated to the rest of the joints.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_TranslateCommand

    def __init__(self, *args):
        _py3dnacalib23_2_4.TranslateCommand_swiginit(self, _py3dnacalib23_2_4.new_TranslateCommand(*args))

    def setTranslation(self, translation):
        r"""
        Method for setting the translation vector.
        :type translation: dnac2::Vector3
        :param translation:
                The translation vector.
        """
        return _py3dnacalib23_2_4.TranslateCommand_setTranslation(self, translation)

    def run(self, output):
        return _py3dnacalib23_2_4.TranslateCommand_run(self, output)

# Register TranslateCommand in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.TranslateCommand_swigregister(TranslateCommand)

ExpressionCalculationType_JointAndCBS = _py3dnacalib23_2_4.ExpressionCalculationType_JointAndCBS
ExpressionCalculationType_Sculpt = _py3dnacalib23_2_4.ExpressionCalculationType_Sculpt
class ExpressionCalculationFilter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _py3dnacalib23_2_4.delete_ExpressionCalculationFilter

    def __init__(self, *args):
        _py3dnacalib23_2_4.ExpressionCalculationFilter_swiginit(self, _py3dnacalib23_2_4.new_ExpressionCalculationFilter(*args))

    def setExpressionIndices(self, expressionIndices):
        return _py3dnacalib23_2_4.ExpressionCalculationFilter_setExpressionIndices(self, expressionIndices)

    def setMaxPSDLevel(self, maxPSDLevel):
        return _py3dnacalib23_2_4.ExpressionCalculationFilter_setMaxPSDLevel(self, maxPSDLevel)

    def setExpressionCalculationType(self, calculationType):
        return _py3dnacalib23_2_4.ExpressionCalculationFilter_setExpressionCalculationType(self, calculationType)

    def getExpressionIndices(self):
        return _py3dnacalib23_2_4.ExpressionCalculationFilter_getExpressionIndices(self)

    def getMaxPSDLevel(self):
        return _py3dnacalib23_2_4.ExpressionCalculationFilter_getMaxPSDLevel(self)

    def getExpressionCalculationType(self):
        return _py3dnacalib23_2_4.ExpressionCalculationFilter_getExpressionCalculationType(self)

# Register ExpressionCalculationFilter in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.ExpressionCalculationFilter_swigregister(ExpressionCalculationFilter)

ExpressionDirtiness__None = _py3dnacalib23_2_4.ExpressionDirtiness__None
ExpressionDirtiness_Sculpt = _py3dnacalib23_2_4.ExpressionDirtiness_Sculpt
ExpressionDirtiness_CorrectiveBlendShape = _py3dnacalib23_2_4.ExpressionDirtiness_CorrectiveBlendShape
ExpressionDirtiness_Joint = _py3dnacalib23_2_4.ExpressionDirtiness_Joint

def __or__(lhs, rhs):
    return _py3dnacalib23_2_4.__or__(lhs, rhs)

def __and__(lhs, rhs):
    return _py3dnacalib23_2_4.__and__(lhs, rhs)

def __xor__(lhs, rhs):
    return _py3dnacalib23_2_4.__xor__(lhs, rhs)

def __invert__(lhs):
    return _py3dnacalib23_2_4.__invert__(lhs)

def __ior__(lhs, rhs):
    return _py3dnacalib23_2_4.__ior__(lhs, rhs)

def __iand__(lhs, rhs):
    return _py3dnacalib23_2_4.__iand__(lhs, rhs)

def __ixor__(lhs, rhs):
    return _py3dnacalib23_2_4.__ixor__(lhs, rhs)
DeltaTransferOption_JointsOnly = _py3dnacalib23_2_4.DeltaTransferOption_JointsOnly
DeltaTransferOption_BlendShapesOnly = _py3dnacalib23_2_4.DeltaTransferOption_BlendShapesOnly
DeltaTransferOption_JointsAndBlendShapes = _py3dnacalib23_2_4.DeltaTransferOption_JointsAndBlendShapes
class RigDelta(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, expressionIndices, rdfReader, memRes=None):
        _py3dnacalib23_2_4.RigDelta_swiginit(self, _py3dnacalib23_2_4.new_RigDelta(expressionIndices, rdfReader, memRes))
    __swig_destroy__ = _py3dnacalib23_2_4.delete_RigDelta

    def getExpressionIndices(self):
        return _py3dnacalib23_2_4.RigDelta_getExpressionIndices(self)

    def getJointDeltas(self, expressionIndex, phaseIndex):
        return _py3dnacalib23_2_4.RigDelta_getJointDeltas(self, expressionIndex, phaseIndex)

    def getCorrectiveBlendShapeVertexIndices(self, expressionIndex, phaseIndex, meshIndex):
        return _py3dnacalib23_2_4.RigDelta_getCorrectiveBlendShapeVertexIndices(self, expressionIndex, phaseIndex, meshIndex)

    def getCorrectiveBlendShapeDeltas(self, expressionIndex, phaseIndex, meshIndex):
        return _py3dnacalib23_2_4.RigDelta_getCorrectiveBlendShapeDeltas(self, expressionIndex, phaseIndex, meshIndex)

    def setJointDeltas(self, expressionIndex, phaseIndex, deltas):
        return _py3dnacalib23_2_4.RigDelta_setJointDeltas(self, expressionIndex, phaseIndex, deltas)

    def setCorrectiveBlendShapeDeltas(self, expressionIndex, phaseIndex, meshIndex, vertexIndices, deltas):
        return _py3dnacalib23_2_4.RigDelta_setCorrectiveBlendShapeDeltas(self, expressionIndex, phaseIndex, meshIndex, vertexIndices, deltas)

# Register RigDelta in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.RigDelta_swigregister(RigDelta)
RigDelta.NoDeltaForExpressionError = _py3dnacalib23_2_4.cvar.RigDelta_NoDeltaForExpressionError


RigDelta.__init__ = arg_preserver_init(RigDelta.__init__)

class Rig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    @staticmethod
    def create(*args):
        return _py3dnacalib23_2_4.Rig_create(*args)

    @staticmethod
    def destroy(instance):
        return _py3dnacalib23_2_4.Rig_destroy(instance)

    def getVertexCount(self, meshIndex):
        return _py3dnacalib23_2_4.Rig_getVertexCount(self, meshIndex)

    def getSculpt(self, expressionIndex, phase, meshIndex):
        return _py3dnacalib23_2_4.Rig_getSculpt(self, expressionIndex, phase, meshIndex)

    def setSculpt(self, *args):
        return _py3dnacalib23_2_4.Rig_setSculpt(self, *args)

    def getJointAbsolute(self, expressionIndex, phase, jointIndex):
        return _py3dnacalib23_2_4.Rig_getJointAbsolute(self, expressionIndex, phase, jointIndex)

    def getJointsAbsolute(self, expressionIndex, phase):
        return _py3dnacalib23_2_4.Rig_getJointsAbsolute(self, expressionIndex, phase)

    def getJointDelta(self, expressionIndex, phase, jointIndex):
        return _py3dnacalib23_2_4.Rig_getJointDelta(self, expressionIndex, phase, jointIndex)

    def getJointsDelta(self, expressionIndex, phase):
        return _py3dnacalib23_2_4.Rig_getJointsDelta(self, expressionIndex, phase)

    def setJointAbsolute(self, expressionIndex, phase, jointIndex, transformation):
        return _py3dnacalib23_2_4.Rig_setJointAbsolute(self, expressionIndex, phase, jointIndex, transformation)

    def setJointsAbsolute(self, *args):
        return _py3dnacalib23_2_4.Rig_setJointsAbsolute(self, *args)

    def setJointDelta(self, expressionIndex, phase, jointIndex, transformation):
        return _py3dnacalib23_2_4.Rig_setJointDelta(self, expressionIndex, phase, jointIndex, transformation)

    def setJointsDelta(self, *args):
        return _py3dnacalib23_2_4.Rig_setJointsDelta(self, *args)

    def getCorrectiveBlendShapeVertexIndices(self, expressionIndex, phase, meshIndex):
        return _py3dnacalib23_2_4.Rig_getCorrectiveBlendShapeVertexIndices(self, expressionIndex, phase, meshIndex)

    def getCorrectiveBlendShapeDeltas(self, expressionIndex, phase, meshIndex):
        return _py3dnacalib23_2_4.Rig_getCorrectiveBlendShapeDeltas(self, expressionIndex, phase, meshIndex)

    def setCorrectiveBlendShape(self, *args):
        return _py3dnacalib23_2_4.Rig_setCorrectiveBlendShape(self, *args)

    def getNeutralMesh(self, meshIndex):
        return _py3dnacalib23_2_4.Rig_getNeutralMesh(self, meshIndex)

    def setNeutralMesh(self, *args):
        return _py3dnacalib23_2_4.Rig_setNeutralMesh(self, *args)

    def getNeutralJoint(self, jointIndex):
        return _py3dnacalib23_2_4.Rig_getNeutralJoint(self, jointIndex)

    def getNeutralJoints(self):
        return _py3dnacalib23_2_4.Rig_getNeutralJoints(self)

    def setNeutralJoint(self, jointIndex, transformation):
        return _py3dnacalib23_2_4.Rig_setNeutralJoint(self, jointIndex, transformation)

    def setNeutralJoints(self, *args):
        return _py3dnacalib23_2_4.Rig_setNeutralJoints(self, *args)

    def setSkinWeightValues(self, meshIndex, vertexIndex, values):
        return _py3dnacalib23_2_4.Rig_setSkinWeightValues(self, meshIndex, vertexIndex, values)

    def setSkinWeightJointIndices(self, meshIndex, vertexIndex, jointIndices):
        return _py3dnacalib23_2_4.Rig_setSkinWeightJointIndices(self, meshIndex, vertexIndex, jointIndices)

    def getSkinWeightValues(self, meshIndex, vertexIndex):
        return _py3dnacalib23_2_4.Rig_getSkinWeightValues(self, meshIndex, vertexIndex)

    def getSkinWeightJointIndices(self, meshIndex, vertexIndex):
        return _py3dnacalib23_2_4.Rig_getSkinWeightJointIndices(self, meshIndex, vertexIndex)

    def calculateExpression(self, expressionIndex):
        return _py3dnacalib23_2_4.Rig_calculateExpression(self, expressionIndex)

    def calculateExpressions(self, *args):
        return _py3dnacalib23_2_4.Rig_calculateExpressions(self, *args)

    def getExpressionCount(self):
        r"""Number of expressions."""
        return _py3dnacalib23_2_4.Rig_getExpressionCount(self)

    def getDependentExpressionIndices(self, expressionIndex):
        return _py3dnacalib23_2_4.Rig_getDependentExpressionIndices(self, expressionIndex)

    def getDirtyExpressionIndices(self):
        r"""Indices of expressions currently marked as dirty."""
        return _py3dnacalib23_2_4.Rig_getDirtyExpressionIndices(self)

    def getDirtyExpressionFlags(self):
        r"""
        Dirty flags of expressions currently marked as dirty.
        Notes: These correspond to indices from getDirtyExpressionIndices().
        """
        return _py3dnacalib23_2_4.Rig_getDirtyExpressionFlags(self)

    def setDirtyExpressionIndices(self, expressionIndices):
        r"""
        Mark expressions as dirty.

        :type expressionIndices: dnac2::ConstArrayView< std::uint16_t >
        :param expressionIndices:
                Indices of expressions to be marked as dirty.
        Notes: 
            This will mark as dirty only the exact expressions that are specified, without marking dependents dirty as well.
        """
        return _py3dnacalib23_2_4.Rig_setDirtyExpressionIndices(self, expressionIndices)

    def clearDirtyExpressionIndices(self, expressionIndices):
        r"""
        Mark expressions as not dirty.

        :type expressionIndices: dnac2::ConstArrayView< std::uint16_t >
        :param expressionIndices:
                Indices of expressions to be marked as clean.
        Notes: 
            This will clear dirtiness of only the exact expressions that are specified, without clearing dependents as well.
        """
        return _py3dnacalib23_2_4.Rig_clearDirtyExpressionIndices(self, expressionIndices)

    def calculateDelta(self, previous, delta):
        r"""
        Calculate deltas for joints and CBSs between current and previous rig states and write them in a RigDelta object.

        :type previous: :py:class:`Rig`
        :param previous:
                Previous rig object to calculate the delta to.
        :type delta: :py:class:`RigDelta`
        :param delta:
                RigDelta object containing calculated deltas.
        """
        return _py3dnacalib23_2_4.Rig_calculateDelta(self, previous, delta)

    def applyDelta(self, delta, sourceExpressionIndex, sourceExpressionPhase, targetExpressionIndex, targetExpressionPhase, option, multiplier):
        r"""
        Apply calculated delta to current rig state.

        :type delta: :py:class:`RigDelta`
        :param delta:
                Previously calculated delta that's applied to current rig.
        """
        return _py3dnacalib23_2_4.Rig_applyDelta(self, delta, sourceExpressionIndex, sourceExpressionPhase, targetExpressionIndex, targetExpressionPhase, option, multiplier)

    def save(self, rigStream):
        r"""
        Save current rig state.

        :type rigStream: :py:class:`BoundedIOStream`
        :param rigStream:
        """
        return _py3dnacalib23_2_4.Rig_save(self, rigStream)

    def setJointPruningThreshold(self, translationThreshold, rotationThreshold, scaleThreshold):
        r"""
        Set the threshold value below which joint deltas will be pruned during the export process.
        :type translationThreshold: float
        :param translationThreshold:
                The threshold to be used for pruning joint translation values only.
        :type rotationThreshold: float
        :param rotationThreshold:
                The threshold to be used for pruning joint rotation values only.
        :type scaleThreshold: float
        :param scaleThreshold:
                The threshold to be used for pruning joint scale values only.
        """
        return _py3dnacalib23_2_4.Rig_setJointPruningThreshold(self, translationThreshold, rotationThreshold, scaleThreshold)

    def setCorrectiveBlendShapePruningThreshold(self, threshold):
        r"""
        Set the threshold value below which corrective blend shapes will be pruned during the export process.
        :type threshold: float
        :param threshold:
                The threshold to be used for pruning corrective blend shapes.
        """
        return _py3dnacalib23_2_4.Rig_setCorrectiveBlendShapePruningThreshold(self, threshold)

    def exportDNA(self, *args):
        r"""
        *Overload 1:*

        Export the DNA file contents into the given DNACalibDNAReader.
        :type output: :py:class:`DNACalibDNAReader`
        :param output:
                The DNACalibDNAReader instance into which the DNA is to be exported.

        |

        *Overload 2:*

        Export the DNA file contents into the given stream.
        :type stream: :py:class:`BoundedIOStream`
        :param stream:
                The stream instance into which the DNA is to be written.
        """
        return _py3dnacalib23_2_4.Rig_exportDNA(self, *args)

# Register Rig in _py3dnacalib23_2_4:
_py3dnacalib23_2_4.Rig_swigregister(Rig)
Rig.InvalidArgumentError = _py3dnacalib23_2_4.cvar.Rig_InvalidArgumentError
Rig.SavingDirtyRigError = _py3dnacalib23_2_4.cvar.Rig_SavingDirtyRigError
Rig.IncompatibleRigDefinitionError = _py3dnacalib23_2_4.cvar.Rig_IncompatibleRigDefinitionError
Rig.ExpressionIndexOutOfBounds = _py3dnacalib23_2_4.cvar.Rig_ExpressionIndexOutOfBounds
Rig.ExpressionCyclicDependency = _py3dnacalib23_2_4.cvar.Rig_ExpressionCyclicDependency
Rig.MaximumInfluencePerVertexError = _py3dnacalib23_2_4.cvar.Rig_MaximumInfluencePerVertexError
Rig.NegativeSkinWeightValuesError = _py3dnacalib23_2_4.cvar.Rig_NegativeSkinWeightValuesError
Rig.RigDefinitionReaderIsNull = _py3dnacalib23_2_4.cvar.Rig_RigDefinitionReaderIsNull
Rig.DNAReaderIsNull = _py3dnacalib23_2_4.cvar.Rig_DNAReaderIsNull

def Rig_create(*args):
    return _py3dnacalib23_2_4.Rig_create(*args)

def Rig_destroy(instance):
    return _py3dnacalib23_2_4.Rig_destroy(instance)


RigImpl = Rig

class RigImplReflectionMixin(type):

    def __getattr__(cls, name):
        return getattr(RigImpl, name)

    def __dir__(cls):
        return [name for name in dir(RigImpl) if name not in ("create","destroy")]

class Rig(with_metaclass(RigImplReflectionMixin, object)):
    __slots__ = ('_args', '_kwargs', '_instance')

    def __init__(self, *args, **kwargs):
        self._args = args
        self._kwargs = kwargs
        self._instance = RigImpl.create(*args, **kwargs)

    def __del__(self):
        RigImpl.destroy(self._instance)

    def _in_slots(self, attr):
        for cls in type(self).__mro__:
            if attr in getattr(cls, '__slots__', []):
                return True
        return False

    def __getattr__(self, attr):
        if self._in_slots(attr):
            return object.__getattr__(self, attr)
        return getattr(self._instance, attr)

    def __setattr__(self, attr, value):
        if self._in_slots(attr):
            object.__setattr__(self, attr, value)
        else:
            setattr(self._instance, attr, value)

    def __dir__(self):
        return [name for name in self._instance.__dir__() if name not in ("create","destroy")]


Rig.__init__ = arg_preserver_init(Rig.__init__)



