//Maya Preference 2023 (Release 1)
//
//

runTimeCommand
	-label ""
	-annotation ""
	-longAnnotation ""
	-category "Custom Scripts"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "mel"
	-command ("timeSliderPasteKey false;")
	PasteKey;

runTimeCommand
	-label ""
	-annotation "samkay"
	-longAnnotation ""
	-category "Custom Scripts"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "mel"
	-command ("string $targets[] = `ls -sl`; \nstring $targetAttrs[] = `selectionConnection -q -obj \ngraphEditor1FromOutliner`;\n\nglobal string $finalAttrs[];\nclear($finalAttrs);\nint $i;\nfor ($i=0; $i<(`size $targetAttrs`); $i++)\n{\nstring $buffer[];\ntokenize $targetAttrs[$i] \".\" $buffer;\n$finalAttrs[$i] = $buffer[1];\n}\n\n// filtering graph editor ---\nselectionConnection -e -clear graphEditor1FromOutliner;\n\nfor ($target in $targets)\n{\nfor ($finalAttr in $finalAttrs)\n{\nstring $filter = $target + \".\" + $finalAttr;\nif ( `objExists $filter` )\n{\nselectionConnection -e -select $filter graphEditor1FromOutliner;\n}\n}\n}")
	samkay;

runTimeCommand
	-label ""
	-annotation "Reset_T"
	-longAnnotation ""
	-category "Custom Scripts"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "python"
	-command ("import maya.cmds as cmds \nobjs = cmds.ls(sl= True) \naxis = ['X','Y','Z'] \nfor obj in objs: \n    for i,j in enumerate(axis): \n        if not cmds.getAttr('{0}.translate{1}'.format(obj, j), lock= True): \n            if cmds.getAttr('{0}.translate{1}'.format(obj, j), keyable= True): \n                cmds.setAttr('{0}.translate{1}'.format(obj, j), 0) \n")
	Reset_T;

runTimeCommand
	-label ""
	-annotation "Reset_R"
	-longAnnotation ""
	-category "Custom Scripts"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "python"
	-command ("import maya.cmds as cmds \nobjs = cmds.ls(sl= True) \naxis = ['X','Y','Z'] \nfor obj in objs: \n    for i,j in enumerate(axis): \n        if not cmds.getAttr('{0}.rotate{1}'.format(obj, j), lock= True): \n            if cmds.getAttr('{0}.rotate{1}'.format(obj, j), keyable= True): \n                cmds.setAttr('{0}.rotate{1}'.format(obj, j), 0) ")
	Reset_R;

runTimeCommand
	-label ""
	-annotation "Reset_S"
	-longAnnotation ""
	-category "Custom Scripts"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "python"
	-command ("import maya.cmds as cmds \nobjs = cmds.ls(sl= True) \naxis = ['X','Y','Z'] \nfor obj in objs: \n    for i,j in enumerate(axis): \n        if not cmds.getAttr('{0}.scale{1}'.format(obj, j), lock= True): \n            if cmds.getAttr('{0}.scale{1}'.format(obj, j), keyable= True): \n                cmds.setAttr('{0}.scale{1}'.format(obj, j), 1) ")
	Reset_S;

runTimeCommand
	-label ""
	-annotation ""
	-longAnnotation ""
	-category "Custom Scripts"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "mel"
	-command ("timeSliderCopyKey;")
	CopyKey;

