//Maya Preference 2020 (Release 1)
//
//
windowPref -topLeftCorner 225 150 -widthHeight 250 400 -maximized false -parentMain true outlinerPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 700 400 -maximized false -parentMain true hyperGraphPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 660 400 -maximized false -parentMain true graphEditor1Window;
windowPref -topLeftCorner 250 200 -widthHeight 1400 400 -maximized false -parentMain true timeEditorPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 660 400 -maximized false -parentMain true dopeSheetPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 1040 600 -maximized false -parentMain true nodeEditorPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 660 400 -maximized false -parentMain true shapePanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 1040 600 -maximized false -parentMain true posePanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 660 400 -maximized false -parentMain true clipEditorPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 524 470 -maximized false -parentMain true devicePanel1Window;
windowPref -topLeftCorner 75 75 -widthHeight 1440 900 -maximized false -parentMain true hyperShadePanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 700 400 -maximized false -parentMain true dynPaintScriptedPanelWindow;
windowPref -topLeftCorner 250 200 -widthHeight 550 562 -maximized false -parentMain true blindDataEditor1Window;
windowPref -topLeftCorner 150 200 -widthHeight 1120 640 -maximized false -parentMain true polyTexturePlacementPanel1Window;
windowPref -topLeftCorner 235 230 -widthHeight 1430 710 -maximized false -parentMain true contentBrowserPanel1Window;
windowPref -topLeftCorner 700 1280 -widthHeight 676 480 -maximized false -parentMain true NewFeatureHighlightWnd;
windowPref -topLeftCorner -11 -1 -widthHeight 1920 1536 -maximized true -parentMain false MayaWindow;
windowPref -topLeftCorner 700 1280 -widthHeight 698 793 -maximized false -parentMain true shelfEditor;
windowPref -topLeftCorner 678 1782 -widthHeight 420 826 -maximized false -parentMain true TopoWrap;
windowPref -topLeftCorner 578 1060 -widthHeight 676 1059 -maximized false -parentMain true pluginManagerWindow;
windowPref -topLeftCorner 270 314 -widthHeight 1203 1070 -maximized false -parentMain true PreferencesWindow;
windowPref -topLeftCorner 700 1280 -widthHeight 750 750 -maximized false -parentMain true FbxWarningWindow;
windowPref -topLeftCorner 678 1032 -widthHeight 1878 1050 -maximized false -parentMain true HotkeyEditor;
windowPref -topLeftCorner 700 1280 -widthHeight 370 113 -maximized false -parentMain true jdsWnd;
windowPref -topLeftCorner 772 1219 -widthHeight 820 526 -maximized false -parentMain true OptionBoxWindow;
