# Copyright Epic Games, Inc. All Rights Reserved.

options = {
    "expressions": {
        "expression": [
            {"expName": "brow_down"},
            {"expName": "brow_lateral"},
            {"expName": "brow_raiseIn"},
            {"expName": "brow_raiseOuter_left"},
            {"expName": "brow_raiseOuter_right"},
            {"expName": "brow_raise_tgt"},
            {"expName": "Bdown_Blateral__browLower_tgt"},
            {"expName": "BraiseIn_Bdown__browInnerRaise_tgt"},
            {"expName": "BraiseIn_Bdown_Blateral_tgt"},
            {"expName": "Braise_Ewiden_tgt"},
            {"expName": "Braise_Eblink_tgt"},
            {"expName": "Braise_ElookDown_tgt"},
            {"expName": "ear_up"},
            {"expName": "eye_blink"},
            {"expName": "ElidPress_Eblink_tgt"},
            {"expName": "eye_widen"},
            {"expName": "eye_squintInner"},
            {"expName": "eye_cheekRaise"},
            {"expName": "EcheekRaise_EsquintInner_tgt"},
            {"expName": "EsquintInner_Eblink_tgt"},
            {"expName": "EcheekRaise_Eblink_tgt"},
            {"expName": "EcheekRaise_EsquintInner_Eblink_tgt"},
            {"expName": "eye_faceScrunch"},
            {"expName": "EfaceScrunch_Eblink_tgt"},
            {"expName": "eye_upperLidUp"},
            {"expName": "eye_relax"},
            {"expName": "eye_lowerLidUp"},
            {"expName": "eye_lowerLidDown"},
            {"expName": "eye_lookUp"},
            {"expName": "eye_lookDown"},
            {"expName": "eye_lookLeft"},
            {"expName": "eye_lookRight"},
            {"expName": "ElookUp_ElookLeft_tgt"},
            {"expName": "ElookUp_ElookRight_tgt"},
            {"expName": "ElookDown_ElookLeft_tgt"},
            {"expName": "ElookDown_ElookRight_tgt"},
            {"expName": "ElookUp_Eblink_tgt"},
            {"expName": "ElookDown_Eblink_tgt"},
            {"expName": "ElookLeft_Eblink_tgt"},
            {"expName": "ElookRight_Eblink_tgt"},
            {"expName": "ElookUp_ElookLeft_Eblink_tgt"},
            {"expName": "ElookUp_ElookRight_Eblink_tgt"},
            {"expName": "ElookDown_ElookLeft_Eblink_tgt"},
            {"expName": "ElookDown_ElookRight_Eblink_tgt"},
            {"expName": "ElookDown_Ewiden_tgt"},
            {"expName": "EcheekRaise_NSwrinkle_tgt"},
            {"expName": "nose_wrinkle_left"},
            {"expName": "nose_wrinkle_right"},
            {"expName": "nose_wrinkle_tgt"},
            {"expName": "nose_wrinkleFull_tgt"},
            {"expName": "NSwrinkle_Jopen_tgt"},
            {"expName": "nose_nostrilsDepress"},
            {"expName": "nose_nostrilsDilate"},
            {"expName": "nose_nostrilsCompress"},
            {"expName": "nose_nasolabialDeepener"},
            {"expName": "cheek_suck"},
            {"expName": "cheek_blow_left"},
            {"expName": "cheek_blow_right"},
            {"expName": "cheek_blow_tgt"},
            {"expName": "Cblow_MlipsBlow_tgt"},
            {"expName": "mouth_lipsBlow"},
            {"expName": "mouth_left"},
            {"expName": "mouth_right"},
            {"expName": "mouth_up"},
            {"expName": "mouth_down"},
            {"expName": "mouth_upperLipRaise_left"},
            {"expName": "mouth_upperLipRaise_right"},
            {"expName": "mouth_upperLipRaise_tgt"},
            {"expName": "MupperLipRaise_Jopen_tgt"},
            {"expName": "mouth_lowerLipDepress_left"},
            {"expName": "mouth_lowerLipDepress_right"},
            {"expName": "mouth_lowerLipDepress_tgt"},
            {"expName": "MlowerLipDepress_Jopen_tgt"},
            {"expName": "MupperLipRaise_MlowerLipDepress_tgt"},
            {"expName": "MupperLipRaise_MlowerLipDepress_Jopen_tgt"},
            {"expName": "mouth_cornerPull_left"},
            {"expName": "mouth_cornerPull_right"},
            {"expName": "mouth_cornerPull_tgt"},
            {"expName": "mouth_stretch_left"},
            {"expName": "mouth_stretch_right"},
            {"expName": "mouth_stretch_tgt"},
            {"expName": "Mstretch_MstretchLipsClose_tgt"},
            {"expName": "McornerPull_Mstretch_tgt"},
            {"expName": "McornerPull_Mstretch_Jopen_tgt"},
            {"expName": "mouth_dimple_left"},
            {"expName": "mouth_dimple_right"},
            {"expName": "mouth_dimple_tgt"},
            {"expName": "mouth_cornerDepress"},
            {"expName": "mouth_press"},
            {"expName": "mouth_lipsPurse"},
            {"expName": "mouth_lipsTowards"},
            {"expName": "mouth_funnel"},
            {"expName": "Mpurse_Mtowards__pucker_tgt"},
            {"expName": "Mpurse_Mfunnel_tgt"},
            {"expName": "Mfunnel_Mtowards_tgt"},
            {"expName": "Mpurse_Mtowards_Mfunnel__oh_tgt"},
            {"expName": "Mpurse_Jopen_tgt"},
            {"expName": "Mtowards_Jopen_tgt"},
            {"expName": "Mfunnel_Jopen_tgt"},
            {"expName": "Mpurse_Mtowards_Jopen__puckerJawOpen_tgt"},
            {"expName": "Mpurse_Mfunnel_Jopen_tgt"},
            {"expName": "Mfunnel_Mtowards_Jopen_tgt"},
            {"expName": "Mpurse_Mtowards_Mfunnel_Jopen__ohJawOpen_tgt"},
            {"expName": "McornerPull_Jopen_tgt"},
            {"expName": "McornerPull_MlowerLipDepress_tgt"},
            {"expName": "McornerPull_MlowerLipDepress_Jopen_tgt"},
            {"expName": "Mdimple_Jopen_tgt"},
            {"expName": "Mstretch_Jopen_tgt"},
            {"expName": "Mfunnel_MupperLipRaise_tgt"},
            {"expName": "Mfunnel_MlowerLipDepress_tgt"},
            {"expName": "Mfunnel_MupperLipRaise_MlowerLipDepress__funnelWide_tgt"},
            {"expName": "Mpress_Jopen_tgt"},
            {"expName": "MlipsTogether_Jopen_tgt"},
            {"expName": "MlipsTogether_Mpress_Jopen__mouthSuck_tgt"},
            {"expName": "MupperLipRaise_NSwrinkle_tgt"},
            {"expName": "MupperLipRaise_McornerDepress_tgt"},
            {"expName": "McornerDepress_NSwrinkle_tgt"},
            {"expName": "McornerDepress_Jopen_tgt"},
            {"expName": "MupperLipRaise_NSwrinkle_McornerDepress_tgt"},
            {"expName": "MupperLipRaise_NSwrinkle_Jopen_tgt"},
            {"expName": "MupperLipRaise_McornerDepress_Jopen_tgt"},
            {"expName": "McornerDepress_NSwrinkle_Jopen_tgt"},
            {"expName": "MupperLipRaise_NSwrinkle_McornerDepress_Jopen_tgt"},
            {"expName": "Mstretch_MupperLipRaise_tgt"},
            {"expName": "Mstretch_MupperLipRaise_Jopen_tgt"},
            {"expName": "mouth_lipsTighten"},
            {"expName": "mouth_lipsPress"},
            {"expName": "McornerPull_Mpurse_tgt"},
            {"expName": "McornerPull_Mtowards_tgt"},
            {"expName": "McornerPull_Mfunnel_tgt"},
            {"expName": "McornerPull_Mpurse_Mtowards__cornerPullPucker_tgt"},
            {"expName": "McornerPull_Mpurse_Mfunnel_tgt"},
            {"expName": "McornerPull_Mfunnel_Mtowards_tgt"},
            {"expName": "McornerPull_Mpurse_Mtowards_Mfunnel__cornerPullOh_tgt"},
            {"expName": "MupperLipRaise_Mtighten_tgt"},
            {"expName": "MlowerLipDepress_Mtighten_tgt"},
            {"expName": "MupperLipRaise_MlowerLipDepress_Mtighten_tgt"},
            {"expName": "mouth_sharpCornerPull"},
            {"expName": "MsharpCornerPull_Jopen_tgt"},
            {"expName": "mouth_lipsPush"},
            {"expName": "mouth_lipsPull"},
            {"expName": "mouth_lipsThin"},
            {"expName": "mouth_lipsThick"},
            {"expName": "mouth_lipsThinInward"},
            {"expName": "mouth_lipsThickInward"},
            {"expName": "mouth_cornerSharpen_tgt"},
            {"expName": "mouth_cornerRounder_tgt"},
            {"expName": "McornerPull_EcheekRaise_tgt"},
            {"expName": "Mstretch_JlowerChinRaise_tgt"},
            {"expName": "Mdimple_MupperLipRaise_tgt"},
            {"expName": "Mdimple_MlowerLipDepress_tgt"},
            {"expName": "Mdimple_MupperLipRaise_MlowerLipDepress__ee_tgt"},
            {"expName": "McornerPull_MsharpCornerPull_tgt"},
            {"expName": "McornerPull_Mdimple_tgt"},
            {"expName": "Mstretch_MlowerLipDepress_tgt"},
            {"expName": "McornerPull_MupperLipRaise_tgt"},
            {"expName": "McornerPull_NSwrinkle_tgt"},
            {"expName": "McornerPull_MupperLipRaise_NSwrinkle_tgt"},
            {"expName": "McornerPull_MupperLipRaise_Jopen_tgt"},
            {"expName": "McornerPull_NSwrinkle_Jopen_tgt"},
            {"expName": "McornerPull_MupperLipRaise_NSwrinkle_Jopen_tgt"},
            {"expName": "Mstretch_NSdepress_tgt"},
            {"expName": "Mpurse_Mtighten_tgt"},
            {"expName": "Mtowards_Mtighten_tgt"},
            {"expName": "Mfunnel_Mtighten_tgt"},
            {"expName": "Mpurse_Mtowards_Mtighten__puckerTighten_tgt"},
            {"expName": "Mpurse_Mfunnel_Mtighten_tgt"},
            {"expName": "Mfunnel_Mtowards_Mtighten_tgt"},
            {"expName": "Mpurse_Mtowards_Mfunnel_Mtighten__ohTighten_tgt"},
            {"expName": "Mstretch_Mpurse_tgt"},
            {"expName": "Mstretch_Mtowards_tgt"},
            {"expName": "Mstretch_Mfunnel_tgt"},
            {"expName": "Mstretch_Mpurse_Mtowards__mouthStretchPucker_tgt"},
            {"expName": "Mstretch_Mpurse_Mfunnel_tgt"},
            {"expName": "Mstretch_Mfunnel_Mtowards_tgt"},
            {"expName": "Mstretch_Mpurse_Mtowards_Mfunnel__mouthStretchOh_tgt"},
            {"expName": "Mdimple_Mpurse_tgt"},
            {"expName": "Mdimple_Mtowards_tgt"},
            {"expName": "Mdimple_Mfunnel_tgt"},
            {"expName": "Mdimple_Mpurse_Mtowards__dimplePucker_tgt"},
            {"expName": "Mdimple_Mpurse_Mfunnel_tgt"},
            {"expName": "Mdimple_Mfunnel_Mtowards_tgt"},
            {"expName": "Mdimple_Mpurse_Mtowards_Mfunnel__dimpleOh_tgt"},
            {"expName": "Mstretch_Mdimple_tgt"},
            {"expName": "McornerPull_Mstretch_Mdimple_tgt"},
            {"expName": "Mstretch_MlowerLipDepress_Jopen_tgt"},
            {"expName": "McornerPull_Mstretch_MupperLipRaise_tgt"},
            {"expName": "McornerPull_Mstretch_MlowerLipDepress_tgt"},
            {"expName": "McornerPull_MlowerLipDepress_MupperLipRaise_tgt"},
            {"expName": "Mstretch_MupperLipRaise_MlowerLipDepress_tgt"},
            {"expName": "McornerPull_Mstretch_MupperLipRaise_MlowerLipDepress_tgt"},
            {"expName": "McornerPull_Mstretch_MupperLipRaise_Jopen_tgt"},
            {"expName": "McornerPull_Mstretch_MlowerLipDepress_Jopen_tgt"},
            {"expName": "McornerPull_MlowerLipDepress_MupperLipRaise_Jopen_tgt"},
            {"expName": "Mstretch_MlowerLipDepress_MupperLipRaise_Jopen_tgt"},
            {"expName": "McornerPull_Mstretch_MupperLipRaise_MlowerLipDepress_Jopen_tgt"},
            {"expName": "Mstretch_NSwrinkle_tgt"},
            {"expName": "Mstretch_MupperLipRaise_NSwrinkle_tgt"},
            {"expName": "McornerPull_MupperLipRaise_Mdimple_tgt"},
            {"expName": "Mstretch_MupperLipRaise_Mdimple_tgt"},
            {"expName": "McornerPull_MlowerLipDepress_Mdimple_tgt"},
            {"expName": "Mstretch_MlowerLipDepress_Mdimple_tgt"},
            {"expName": "McornerPull_Mstretch_MupperLipRaise_Mdimple_tgt"},
            {"expName": "McornerPull_Mstretch_MlowerLipDepress_Mdimple_tgt"},
            {"expName": "McornerPull_MupperLipRaise_MlowerLipDepress_Mdimple_tgt"},
            {"expName": "Mstretch_MupperLipRaise_MlowerLipDepress_Mdimple_tgt"},
            {"expName": "McornerPull_Mstretch_MupperLipRaise_MlowerLipDepress_Mdimple_tgt"},
            {"expName": "McornerPull_Mdimple_Jopen_tgt"},
            {"expName": "Mstretch_Mdimple_Jopen_tgt"},
            {"expName": "McornerPull_Mstretch_Mdimple_Jopen_tgt"},
            {"expName": "McornerPull_Mstretch_NSwrinkle_tgt"},
            {"expName": "McornerPull_Mstretch_MupperLipRaise_NSwrinkle_tgt"},
            {"expName": "Mstretch_NSwrinkle_Jopen_tgt"},
            {"expName": "Mstretch_MupperLipRaise_NSwrinkle_Jopen_tgt"},
            {"expName": "McornerPull_Mstretch_NSwrinkle_Jopen_tgt"},
            {"expName": "McornerPull_Mstretch_MupperLipRaise_NSwrinkle_Jopen_tgt"},
            {"expName": "McornerPull_JopenExtreme_tgt"},
            {"expName": "Mstretch_JopenExtreme_tgt"},
            {"expName": "MupperLipRaise_JopenExtreme_tgt"},
            {"expName": "MlowerLipDepress_JopenExtreme_tgt"},
            {"expName": "McornerPull_Mstretch_JopenExtreme_tgt"},
            {"expName": "McornerPull_MupperLipRaise_JopenExtreme_tgt"},
            {"expName": "Mstretch_MupperLipRaise_JopenExtreme_tgt"},
            {"expName": "McornerPull_MlowerLipDepress_JopenExtreme_tgt"},
            {"expName": "Mstretch_MlowerLipDepress_JopenExtreme_tgt"},
            {"expName": "MupperLipRaise_MlowerLipDepress_JopenExtreme_tgt"},
            {"expName": "McornerPull_Mstretch_MupperLipRaise_JopenExtreme_tgt"},
            {"expName": "McornerPull_Mstretch_MlowerLipDepress_JopenExtreme_tgt"},
            {"expName": "McornerPull_MlowerLipDepress_MupperLipRaise_JopenExtreme_tgt"},
            {"expName": "Mstretch_MlowerLipDepress_MupperLipRaise_JopenExtreme_tgt"},
            {"expName": "McornerPull_Mstretch_MupperLipRaise_MlowerLipDepress_JopenExtreme_tgt"},
            {"expName": "mouth_upperLipTowardsTeeth"},
            {"expName": "mouth_lowerLipTowardsTeeth"},
            {"expName": "mouth_upperLipShiftLeft"},
            {"expName": "mouth_upperLipShiftRight"},
            {"expName": "mouth_lowerLipShiftLeft"},
            {"expName": "mouth_lowerLipShiftRight"},
            {"expName": "mouth_upperLipRollIn"},
            {"expName": "mouth_upperLipRollOut"},
            {"expName": "mouth_lowerLipRollIn"},
            {"expName": "mouth_lowerLipRollOut"},
            {"expName": "mouth_cornersUp"},
            {"expName": "mouth_cornersDown"},
            {"expName": "mouth_cornersWide"},
            {"expName": "mouth_cornersNarrow"},
            {"expName": "jaw_open"},
            {"expName": "jaw_left"},
            {"expName": "jaw_right"},
            {"expName": "jaw_fwd"},
            {"expName": "jaw_back"},
            {"expName": "Jleft_Jopen_tgt"},
            {"expName": "Jright_Jopen_tgt"},
            {"expName": "Jleft_MlipsTogether_tgt"},
            {"expName": "Jright_MlipsTogether_tgt"},
            {"expName": "Jleft_MlipsTogether_Jopen_tgt"},
            {"expName": "Jright_MlipsTogether_Jopen_tgt"},
            {"expName": "jaw_clench"},
            {"expName": "jaw_lowerChinRaise"},
            {"expName": "JlowerChinRaise_JupperChinRaise_tgt"},
            {"expName": "JlowerChinRaise_MupperLipRaise_tgt"},
            {"expName": "JlowerChinRaise_Jopen_tgt"},
            {"expName": "jaw_chinCompress"},
            {"expName": "jaw_openExtreme_tgt"},
            {"expName": "neck_stretch"},
            {"expName": "NKstretch_Mstretch_tgt"},
            {"expName": "NKstretch_Jopen_tgt"},
            {"expName": "NKstretch_Mstretch_Jopen_tgt"},
            {"expName": "neck_swallow"},
            {"expName": "neck_mastoidContract"},
            {"expName": "neck_throatDown"},
            {"expName": "neck_throatUp"},
            {"expName": "neck_digastricDown"},
            {"expName": "neck_digastricUp"},
            {"expName": "neck_throatExhale"},
            {"expName": "neck_throatInhale"},
            {"expName": "head_turnUp_tgt"},
            {"expName": "head_turnDown_tgt"},
            {"expName": "head_turnLeft_tgt"},
            {"expName": "head_turnRight_tgt"},
            {"expName": "head_tiltLeft_tgt"},
            {"expName": "head_tiltRight_tgt"},
            {"expName": "head_fwd_tgt"},
            {"expName": "head_back_tgt"},
            {"expName": "head_sideLeft_tgt"},
            {"expName": "head_sideRight_tgt"},
            {"expName": "HturnUp_NKstretch_tgt"},
            {"expName": "HturnDown_NKstretch_tgt"},
            {"expName": "HturnLeft_NKstretch_tgt"},
            {"expName": "HturnRight_NKstretch_tgt"},
            {"expName": "HtiltLeft_NKstretch_tgt"},
            {"expName": "HtiltRight_NKstretch_tgt"},
            {"expName": "HturnUp_NKthroatExhale_tgt"},
            {"expName": "HturnUp_NKthroatInhale_tgt"},
            {"expName": "HturnDown_NKthroatExhale_tgt"},
            {"expName": "HturnDown_NKthroatInhale_tgt"},
        ]
    },
    "passes": {
        "pass": [
            {
                "jointOptions": {
                    "jointOption": [
                        {"name": "FACIAL_L_EyeCornerInner", "r": True, "t": True},
                        {"name": "FACIAL_R_EyeCornerInner", "r": True, "t": True},
                        {"name": "FACIAL_L_EyeCornerOuter", "r": True, "t": True},
                        {"name": "FACIAL_R_EyeCornerOuter", "r": True, "t": True},
                        {"name": "FACIAL_L_EyelidLowerA", "r": True, "t": False},
                        {"name": "FACIAL_R_EyelidLowerA", "r": True, "t": False},
                        {"name": "FACIAL_R_EyelidUpperA", "r": True, "t": False},
                        {"name": "FACIAL_L_EyelidUpperA", "r": True, "t": False},
                    ]
                },
                "bendingWeight": "0.0",
                "meshName": "headMatchPass1_mesh",
                "nIterations": "10",
                "name": "pass1_eyelidsContact",
                "paintConstraintSplitMap": "JO_01_pass1_eyelidsContact_1",
                "rotationRegularization": "0.5",
                "sculptMesh": "head_lod0_mesh",
                "startType": "1",
                "strainWeight": "0.0",
                "translationRegularization": "0.0",
            },
            {
                "jointOptions": {
                    "jointOption": [
                        {"name": "FACIAL_C_AdamsApple", "r": True, "t": True},
                        {"name": "FACIAL_L_Temple", "r": True, "t": True},
                        {"name": "FACIAL_R_Temple", "r": True, "t": True},
                        {"name": "FACIAL_C_Forehead", "r": True, "t": True},
                        {"name": "FACIAL_L_ForeheadIn", "r": True, "t": True},
                        {"name": "FACIAL_R_ForeheadIn", "r": True, "t": True},
                        {"name": "FACIAL_L_ForeheadMid", "r": True, "t": True},
                        {"name": "FACIAL_R_ForeheadMid", "r": True, "t": True},
                        {"name": "FACIAL_L_ForeheadOut", "r": True, "t": True},
                        {"name": "FACIAL_R_ForeheadOut", "r": True, "t": True},
                        {"name": "FACIAL_L_EyesackUpper", "r": True, "t": True},
                        {"name": "FACIAL_R_EyesackUpper", "r": True, "t": True},
                        {
                            "name": "FACIAL_L_EyelidUpperFurrow",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_R_EyelidUpperFurrow",
                            "r": True,
                            "t": True,
                        },
                        {"name": "FACIAL_L_EyelidUpperB", "r": True, "t": True},
                        {"name": "FACIAL_R_EyelidUpperB", "r": True, "t": True},
                        {"name": "FACIAL_L_EyelidLowerB", "r": True, "t": True},
                        {"name": "FACIAL_R_EyelidLowerB", "r": True, "t": True},
                        {"name": "FACIAL_L_EyesackLower", "r": True, "t": True},
                        {"name": "FACIAL_R_EyesackLower", "r": True, "t": True},
                        {"name": "FACIAL_L_CheekInner", "r": True, "t": True},
                        {"name": "FACIAL_R_CheekInner", "r": True, "t": True},
                        {"name": "FACIAL_L_CheekOuter", "r": True, "t": True},
                        {"name": "FACIAL_R_CheekOuter", "r": True, "t": True},
                        {"name": "FACIAL_C_NoseBridge", "r": True, "t": True},
                        {"name": "FACIAL_L_NasolabialBulge", "r": True, "t": True},
                        {"name": "FACIAL_R_NasolabialBulge", "r": True, "t": True},
                        {"name": "FACIAL_L_NasolabialFurrow", "r": True, "t": True},
                        {"name": "FACIAL_R_NasolabialFurrow", "r": True, "t": True},
                        {"name": "FACIAL_L_CheekLower", "r": True, "t": True},
                        {"name": "FACIAL_R_CheekLower", "r": True, "t": True},
                        {"name": "FACIAL_L_Ear", "r": True, "t": True},
                        {"name": "FACIAL_R_Ear", "r": True, "t": True},
                        {"name": "FACIAL_C_NoseLower", "r": True, "t": True},
                        {"name": "FACIAL_C_NoseTip", "r": True, "t": True},
                        {"name": "FACIAL_L_Nostril", "r": True, "t": True},
                        {"name": "FACIAL_R_Nostril", "r": True, "t": True},
                        {"name": "FACIAL_C_LipUpper", "r": True, "t": True},
                        {"name": "FACIAL_L_LipUpper", "r": True, "t": True},
                        {"name": "FACIAL_R_LipUpper", "r": True, "t": True},
                        {"name": "FACIAL_L_LipUpperOuter", "r": True, "t": True},
                        {"name": "FACIAL_R_LipUpperOuter", "r": True, "t": True},
                        {"name": "FACIAL_L_LipCorner", "r": True, "t": True},
                        {"name": "FACIAL_R_LipCorner", "r": True, "t": True},
                        {"name": "FACIAL_L_Masseter", "r": True, "t": True},
                        {"name": "FACIAL_R_Masseter", "r": True, "t": True},
                        {"name": "FACIAL_C_UnderChin", "r": True, "t": True},
                        {"name": "FACIAL_L_UnderChin", "r": True, "t": True},
                        {"name": "FACIAL_R_UnderChin", "r": True, "t": True},
                        {"name": "FACIAL_C_LipLower", "r": True, "t": True},
                        {"name": "FACIAL_L_LipLower", "r": True, "t": True},
                        {"name": "FACIAL_R_LipLower", "r": True, "t": True},
                        {"name": "FACIAL_L_LipLowerOuter", "r": True, "t": True},
                        {"name": "FACIAL_R_LipLowerOuter", "r": True, "t": True},
                        {"name": "FACIAL_C_Jawline", "r": True, "t": True},
                        {"name": "FACIAL_L_Jawline", "r": True, "t": True},
                        {"name": "FACIAL_R_Jawline", "r": True, "t": True},
                        {"name": "FACIAL_L_ChinSide", "r": True, "t": True},
                        {"name": "FACIAL_R_ChinSide", "r": True, "t": True},
                        {"name": "FACIAL_C_Chin", "r": True, "t": True},
                    ]
                },
                "bendingWeight": "0.0",
                "meshName": "headMatchPass1_mesh",
                "nIterations": "10",
                "name": "pass1_default",
                "paintConstraintSplitMap": "JO_02_pass1_default_1",
                "rotationRegularization": "1.0",
                "sculptMesh": "head_lod0_mesh",
                "startType": "1",
                "strainWeight": "0.0",
                "translationRegularization": "0.0",
            },
            {
                "jointOptions": {
                    "jointOption": [
                        {"name": "FACIAL_C_LipUpper", "r": False, "t": True},
                        {"name": "FACIAL_L_LipUpper", "r": False, "t": True},
                        {"name": "FACIAL_R_LipUpper", "r": False, "t": True},
                        {"name": "FACIAL_L_LipUpperOuter", "r": False, "t": True},
                        {"name": "FACIAL_R_LipUpperOuter", "r": False, "t": True},
                        {"name": "FACIAL_C_LipLower", "r": False, "t": True},
                        {"name": "FACIAL_L_LipLower", "r": False, "t": True},
                        {"name": "FACIAL_R_LipLower", "r": False, "t": True},
                        {"name": "FACIAL_L_LipLowerOuter", "r": False, "t": True},
                        {"name": "FACIAL_R_LipLowerOuter", "r": False, "t": True},
                    ]
                },
                "bendingWeight": "0.0",
                "meshName": "headMatchPass1_mesh",
                "nIterations": "10",
                "name": "pass1_lipsContact",
                "paintConstraintSplitMap": "JO_04_pass1_lipsContact_1",
                "rotationRegularization": "1.0",
                "sculptMesh": "head_lod0_mesh",
                "startType": "0",
                "strainWeight": "0.0",
                "translationRegularization": "0.0",
            },
        ]
    },
    "name": "JO_01_pass1_default",
}
