# Copyright Epic Games, Inc. All Rights Reserved.

options = {
    "expressions": {
        "expression": [
            {"expName": "mouth_upperLipBite"},
            {"expName": "mouth_lowerLipBite"},
            {"expName": "mouth_lipsBite_tgt"},
            {"expName": "MupperLipBite_Jopen_tgt"},
            {"expName": "MlowerLipBite_Jopen_tgt"},
            {"expName": "MlowerLipBite_MupperLipBite_Jopen_tgt"},
        ]
    },
    "passes": {
        "pass": [
            {
                "jointOptions": {
                    "jointOption": [
                        {"name": "FACIAL_L_EyeCornerInner", "r": True, "t": True},
                        {"name": "FACIAL_R_EyeCornerInner", "r": True, "t": True},
                        {"name": "FACIAL_L_EyeCornerOuter", "r": True, "t": True},
                        {"name": "FACIAL_R_EyeCornerOuter", "r": True, "t": True},
                        {"name": "FACIAL_L_EyelidLowerA", "r": True, "t": False},
                        {"name": "FACIAL_R_EyelidLowerA", "r": True, "t": False},
                        {"name": "FACIAL_R_EyelidUpperA", "r": True, "t": False},
                        {"name": "FACIAL_L_EyelidUpperA", "r": True, "t": False},
                    ]
                },
                "bendingWeight": "0.0",
                "meshName": "headMatchPass1_mesh",
                "nIterations": "10",
                "name": "pass1_eyelidsContact",
                "paintConstraintSplitMap": "JO_01_pass1_eyelidsContact_1",
                "rotationRegularization": "0.5",
                "sculptMesh": "head_lod0_mesh",
                "startType": "1",
                "strainWeight": "0.0",
                "translationRegularization": "0.0",
            },
            {
                "jointOptions": {
                    "jointOption": [
                        {"name": "FACIAL_C_AdamsApple", "r": True, "t": True},
                        {"name": "FACIAL_L_Temple", "r": True, "t": True},
                        {"name": "FACIAL_R_Temple", "r": True, "t": True},
                        {"name": "FACIAL_C_Forehead", "r": True, "t": True},
                        {"name": "FACIAL_L_ForeheadIn", "r": True, "t": True},
                        {"name": "FACIAL_R_ForeheadIn", "r": True, "t": True},
                        {"name": "FACIAL_L_ForeheadMid", "r": True, "t": True},
                        {"name": "FACIAL_R_ForeheadMid", "r": True, "t": True},
                        {"name": "FACIAL_L_ForeheadOut", "r": True, "t": True},
                        {"name": "FACIAL_R_ForeheadOut", "r": True, "t": True},
                        {"name": "FACIAL_L_EyesackUpper", "r": True, "t": True},
                        {"name": "FACIAL_R_EyesackUpper", "r": True, "t": True},
                        {
                            "name": "FACIAL_L_EyelidUpperFurrow",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_R_EyelidUpperFurrow",
                            "r": True,
                            "t": True,
                        },
                        {"name": "FACIAL_L_EyelidUpperB", "r": True, "t": True},
                        {"name": "FACIAL_R_EyelidUpperB", "r": True, "t": True},
                        {"name": "FACIAL_L_EyelidLowerB", "r": True, "t": True},
                        {"name": "FACIAL_R_EyelidLowerB", "r": True, "t": True},
                        {"name": "FACIAL_L_EyesackLower", "r": True, "t": True},
                        {"name": "FACIAL_R_EyesackLower", "r": True, "t": True},
                        {"name": "FACIAL_L_CheekInner", "r": True, "t": True},
                        {"name": "FACIAL_R_CheekInner", "r": True, "t": True},
                        {"name": "FACIAL_L_CheekOuter", "r": True, "t": True},
                        {"name": "FACIAL_R_CheekOuter", "r": True, "t": True},
                        {"name": "FACIAL_C_NoseBridge", "r": True, "t": True},
                        {"name": "FACIAL_L_NasolabialBulge", "r": True, "t": True},
                        {"name": "FACIAL_R_NasolabialBulge", "r": True, "t": True},
                        {"name": "FACIAL_L_NasolabialFurrow", "r": True, "t": True},
                        {"name": "FACIAL_R_NasolabialFurrow", "r": True, "t": True},
                        {"name": "FACIAL_L_CheekLower", "r": True, "t": True},
                        {"name": "FACIAL_R_CheekLower", "r": True, "t": True},
                        {"name": "FACIAL_L_Ear", "r": True, "t": True},
                        {"name": "FACIAL_R_Ear", "r": True, "t": True},
                        {"name": "FACIAL_C_NoseLower", "r": True, "t": True},
                        {"name": "FACIAL_C_NoseTip", "r": True, "t": True},
                        {"name": "FACIAL_L_Nostril", "r": True, "t": True},
                        {"name": "FACIAL_R_Nostril", "r": True, "t": True},
                        {"name": "FACIAL_C_LipUpper", "r": True, "t": True},
                        {"name": "FACIAL_L_LipUpper", "r": True, "t": True},
                        {"name": "FACIAL_R_LipUpper", "r": True, "t": True},
                        {"name": "FACIAL_L_LipUpperOuter", "r": True, "t": True},
                        {"name": "FACIAL_R_LipUpperOuter", "r": True, "t": True},
                        {"name": "FACIAL_L_LipCorner", "r": True, "t": True},
                        {"name": "FACIAL_R_LipCorner", "r": True, "t": True},
                        {"name": "FACIAL_L_Masseter", "r": True, "t": True},
                        {"name": "FACIAL_R_Masseter", "r": True, "t": True},
                        {"name": "FACIAL_C_UnderChin", "r": True, "t": True},
                        {"name": "FACIAL_L_UnderChin", "r": True, "t": True},
                        {"name": "FACIAL_R_UnderChin", "r": True, "t": True},
                        {"name": "FACIAL_C_LipLower", "r": True, "t": True},
                        {"name": "FACIAL_L_LipLower", "r": True, "t": True},
                        {"name": "FACIAL_R_LipLower", "r": True, "t": True},
                        {"name": "FACIAL_L_LipLowerOuter", "r": True, "t": True},
                        {"name": "FACIAL_R_LipLowerOuter", "r": True, "t": True},
                        {"name": "FACIAL_C_Jawline", "r": True, "t": True},
                        {"name": "FACIAL_L_Jawline", "r": True, "t": True},
                        {"name": "FACIAL_R_Jawline", "r": True, "t": True},
                        {"name": "FACIAL_L_ChinSide", "r": True, "t": True},
                        {"name": "FACIAL_R_ChinSide", "r": True, "t": True},
                        {"name": "FACIAL_C_Chin", "r": True, "t": True},
                    ]
                },
                "bendingWeight": "0.0",
                "meshName": "headMatchPass1_mesh",
                "nIterations": "10",
                "name": "pass1_default",
                "paintConstraintSplitMap": "JO_02_pass1_default_1",
                "rotationRegularization": "1.0",
                "sculptMesh": "head_lod0_mesh",
                "startType": "1",
                "strainWeight": "0.0",
                "translationRegularization": "0.0",
            },
            {
                "jointOptions": {
                    "jointOption": [
                        {"name": "FACIAL_C_LipUpper", "r": True, "t": True},
                        {"name": "FACIAL_L_LipUpper", "r": True, "t": True},
                        {"name": "FACIAL_R_LipUpper", "r": True, "t": True},
                        {"name": "FACIAL_L_LipUpperOuter", "r": True, "t": True},
                        {"name": "FACIAL_R_LipUpperOuter", "r": True, "t": True},
                        {"name": "FACIAL_C_LipLower", "r": True, "t": True},
                        {"name": "FACIAL_L_LipLower", "r": True, "t": True},
                        {"name": "FACIAL_R_LipLower", "r": True, "t": True},
                        {"name": "FACIAL_L_LipLowerOuter", "r": True, "t": True},
                        {"name": "FACIAL_R_LipLowerOuter", "r": True, "t": True},
                    ]
                },
                "bendingWeight": "0.0",
                "meshName": "headMatchPass1_mesh",
                "nIterations": "10",
                "name": "pass1_rolls",
                "paintConstraintSplitMap": "JO_03_pass1_rolls_1",
                "rotationRegularization": "0.5",
                "sculptMesh": "head_lod0_mesh",
                "startType": "1",
                "strainWeight": "0.0",
                "translationRegularization": "0.0",
            },
            {
                "jointOptions": {
                    "jointOption": [
                        {"name": "FACIAL_C_LipUpper", "r": False, "t": True},
                        {"name": "FACIAL_L_LipUpper", "r": False, "t": True},
                        {"name": "FACIAL_R_LipUpper", "r": False, "t": True},
                        {"name": "FACIAL_L_LipUpperOuter", "r": False, "t": True},
                        {"name": "FACIAL_R_LipUpperOuter", "r": False, "t": True},
                        {"name": "FACIAL_C_LipLower", "r": False, "t": True},
                        {"name": "FACIAL_L_LipLower", "r": False, "t": True},
                        {"name": "FACIAL_R_LipLower", "r": False, "t": True},
                        {"name": "FACIAL_L_LipLowerOuter", "r": False, "t": True},
                        {"name": "FACIAL_R_LipLowerOuter", "r": False, "t": True},
                    ]
                },
                "bendingWeight": "0.0",
                "meshName": "headMatchPass1_mesh",
                "nIterations": "10",
                "name": "pass1_lipsContactRollIn",
                "paintConstraintSplitMap": "JO_05_pass1_lipsContactRollIn_1",
                "rotationRegularization": "1.0",
                "sculptMesh": "head_lod0_mesh",
                "startType": "0",
                "strainWeight": "0.0",
                "translationRegularization": "0.0",
            },
        ]
    },
    "name": "JO_06_pass1_bites",
}
