# Copyright Epic Games, Inc. All Rights Reserved.

options = {
    "expressions": {
        "expression": [
            {"expName": "tongue_up_tgt"},
            {"expName": "tongue_down_tgt"},
            {"expName": "tongue_left_tgt"},
            {"expName": "tongue_right_tgt"},
            {"expName": "tongue_out_tgt"},
            {"expName": "tongue_in_tgt"},
            {"expName": "tongue_bendUp_tgt"},
            {"expName": "tongue_bendDown_tgt"},
            {"expName": "tongue_twistLeft_tgt"},
            {"expName": "tongue_twistRight_tgt"},
            {"expName": "tongue_tipUp_tgt"},
            {"expName": "tongue_tipDown_tgt"},
            {"expName": "tongue_tipLeft_tgt"},
            {"expName": "tongue_tipRight_tgt"},
            {"expName": "tongue_wide_tgt"},
            {"expName": "tongue_narrow_tgt"},
            {"expName": "tongue_press_tgt"},
            {"expName": "tongue_thick_tgt"},
            {"expName": "tongue_thin_tgt"},
            {"expName": "tongue_retraction_tgt"},
            {"expName": "tongue_dartingOut_tgt"},
            {"expName": "tongue_protrusion_tgt"},
            {"expName": "tongue_outLeft_tgt"},
            {"expName": "tongue_outRight_tgt"},
            {"expName": "tongue_narrowLeft_tgt"},
            {"expName": "tongue_narrowRight_tgt"},
            {"expName": "tongue_outBendUp_tgt"},
            {"expName": "tongue_outBendDown_tgt"},
            {"expName": "tongue_outUp_tgt"},
            {"expName": "tongue_upBendUp_tgt"},
            {"expName": "tongue_upBendDown_tgt"},
            {"expName": "tongue_bendUpTwistLeft_tgt"},
            {"expName": "tongue_bendUpTwistRight_tgt"},
            {"expName": "tongue_bendDownTwistLeft_tgt"},
            {"expName": "tongue_bendDownTwistRight_tgt"},
            {"expName": "tongue_lateralLeft_tgt"},
            {"expName": "tongue_lateralRight_tgt"},
            {"expName": "tongue_elevation_tgt"},
            {"expName": "tongue_depression_tgt"},
        ]
    },
    "passes": {
        "pass": [
            {
                "jointOptions": {
                    "jointOption": [
                        {"name": "FACIAL_C_Tongue1", "r": True, "t": True},
                        {"name": "FACIAL_C_Tongue2", "r": True, "t": True},
                        {"name": "FACIAL_C_Tongue3", "r": True, "t": True},
                        {"name": "FACIAL_C_Tongue4", "r": True, "t": True},
                    ]
                },
                "bendingWeight": "0.0",
                "meshName": "teeth_lod0_mesh",
                "nIterations": "10",
                "name": "pass1_tongueDefault",
                "paintConstraintSplitMap": "JO_13_pass1_tongueDefault_1",
                "rotationRegularization": "0.5",
                "sculptMesh": "teeth_lod0_mesh",
                "startType": "1",
                "strainWeight": "0.0",
                "translationRegularization": "0.0",
            },
            {
                "jointOptions": {
                    "jointOption": [
                        {"name": "FACIAL_C_TongueUpper1", "r": True, "t": True},
                        {"name": "FACIAL_L_TongueSide1", "r": True, "t": True},
                        {"name": "FACIAL_R_TongueSide1", "r": True, "t": True},
                        {"name": "FACIAL_C_TongueUpper2", "r": True, "t": True},
                        {"name": "FACIAL_L_TongueSide2", "r": True, "t": True},
                        {"name": "FACIAL_R_TongueSide2", "r": True, "t": True},
                        {"name": "FACIAL_C_TongueUpper3", "r": True, "t": True},
                        {"name": "FACIAL_C_TongueLower3", "r": True, "t": True},
                        {"name": "FACIAL_L_TongueSide3", "r": True, "t": True},
                        {"name": "FACIAL_R_TongueSide3", "r": True, "t": True},
                        {"name": "FACIAL_L_TongueSide4", "r": True, "t": True},
                        {"name": "FACIAL_R_TongueSide4", "r": True, "t": True},
                    ]
                },
                "bendingWeight": "0.0",
                "meshName": "teeth_lod0_mesh",
                "nIterations": "10",
                "name": "pass2_tongueDefault",
                "paintConstraintSplitMap": "JO_14_pass2_tongueDefault_1",
                "rotationRegularization": "0.5",
                "sculptMesh": "teeth_lod0_mesh",
                "startType": "1",
                "strainWeight": "0.0",
                "translationRegularization": "0.0",
            },
        ]
    },
    "name": "JO_10_pass12_tongue",
}
