global proc shelf_Rendering_User () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;

    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 0
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Render diagnostics not supported by Maya Hardware 2.0" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.4 0.454902 
        -align "center" 
        -label "Render Diagnostics" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "renderDiagnostics.png" 
        -image1 "renderDiagnostics.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "mayaSoftwareRenderDiagnostics" 
        -sourceType "mel" 
        -commandRepeatable 1
        -flat 1
    ;

    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Cancel batch render" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "Cancel Batch Render" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "abortBatchRender.png" 
        -image1 "abortBatchRender.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "batchRender" 
        -sourceType "mel" 
        -commandRepeatable 1
        -flat 1
    ;

    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Display the batch render image" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "Show Batch Render" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "showBatchRender.png" 
        -image1 "showBatchRender.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "batchRender -showImage true" 
        -sourceType "mel" 
        -commandRepeatable 1
        -flat 1
    ;
} 
