//Maya Preference 2023 (Release 1)
//
//

//
// The hotkey set
//
hotkeySet -source "Maya_Default" -current ngSkinTools2;
//
// The hotkey contexts and hotkeys
//
hotkey -keyShortcut "t" -name ("ngskintools_2_ToggleOriginalMeshNameCommand");
hotkey -keyShortcut "F6" -name ("GraphEditorNameCommand");
hotkey -keyShortcut "v" -ctl -name ("PasteKeyNameCommand");
hotkey -keyShortcut "e" -ctl -sht -name ("");
hotkey -keyShortcut "z" -ctl -sht -name ("SelectHierarchyNameCommand");
hotkey -keyShortcut "~" -name ("CenterPivotNameCommand");
hotkey -keyShortcut "w" -ctl -sht -name ("");
hotkey -keyShortcut "s" -name ("ngskintools_2_SampleInfluenceOnNameCommand");
hotkey -keyShortcut "r" -alt -sht -name ("Reset_SNameCommand");
hotkey -keyShortcut "b" -releaseName ("ngskintools_2_BrushSizeOffNameCommand");
hotkey -keyShortcut "s" -releaseName ("ngskintools_2_SampleInfluenceOffNameCommand");
hotkey -keyShortcut "b" -name ("ngskintools_2_BrushSizeOnNameCommand");
hotkey -keyShortcut "i" -name ("ngskintools_2_SetBrushIntensityNameCommand");
hotkey -keyShortcut "s" -alt -sht -name ("");
hotkey -keyShortcut "h" -name ("ngskintools_2_ToggleHelpNameCommand");
hotkey -keyShortcut "!" -name ("FreezeTransformationsNameCommand");
hotkey -keyShortcut "f" -name ("ngskintools_2_ViewFitInfluenceNameCommand");
hotkey -keyShortcut "u" -releaseName ("");
hotkey -keyShortcut "u" -name ("samkayNameCommand");
hotkey -keyShortcut "f" -ctl -name ("ngskintools_2_PaintFloodNameCommand");
hotkey -keyShortcut "e" -alt -sht -name ("Reset_RNameCommand");
hotkey -keyShortcut "F5" -name ("NodeEditorWindowNameCommand");
hotkey -keyShortcut "w" -alt -sht -name ("Reset_TNameCommand");
hotkey -keyShortcut "+" -ctl -name ("");
hotkey -keyShortcut "r" -ctl -sht -name ("ReferenceEditorNameCommand");
hotkey -keyShortcut "d" -name ("ngskintools_2_CycleWeightsDisplayModeNameCommand");
hotkey -keyShortcut "F12" -name ("HotkeyPreferencesWindowNameCommand");
hotkey -keyShortcut "c" -ctl -name ("CopyKeyNameCommand");
hotkeyCtx -type "Editor" -addClient "polyTexturePlacementPanel";
hotkeyCtx -type "Editor" -addClient "profilerPanel";
hotkeyCtx -type "Editor" -addClient "outlinerPanel";
hotkeyCtx -type "Editor" -addClient "hyperGraphPanel";
hotkeyCtx -type "Editor" -addClient "posePanel";
hotkeyCtx -type "Editor" -addClient "hyperShadePanel";
hotkeyCtx -type "Editor" -addClient "nodeEditorPanel";
hotkeyCtx -type "Editor" -addClient "graphEditor";
hotkeyCtx -type "Editor" -addClient "shapePanel";
hotkeyCtx -type "Editor" -addClient "timeEditorPanel";
hotkeyCtx -type "Tool" -addClient "texCutContext";
hotkeyCtx -type "Tool" -addClient "texSculptCacheContext";
hotkeyCtx -type "Tool" -addClient "sculptMeshCache";
hotkeyCtx -type "Tool" -addClient "Unfold3DBrush";
hotkeyCtx -type "Tool" -addClient "bpDraw";
hotkeyCtx -type "Tool" -addClient "ngst2PaintContext";
hotkeyCtx -type "Tool" -addClient "polyCutUV";
hotkeyCtx -type "Tool" -addClient "xgmIGBrush";
hotkeyCtx -type "Tool" -addClient "SymmetrizeUVBrush";
