# Copyright Epic Games, Inc. All Rights Reserved.

options = {
    "expressions": {
        "expression": [
            {"expName": "mouth_sticky_tgt"},
            {"expName": "mouth_lipsSticky_tgt"},
        ]
    },
    "passes": {
        "pass": [
            {
                "jointOptions": {
                    "jointOption": [
                        {"name": "FACIAL_C_LipLower1", "r": True, "t": True},
                        {"name": "FACIAL_C_LipLower2", "r": True, "t": True},
                        {"name": "FACIAL_C_LipLower3", "r": True, "t": True},
                        {"name": "FACIAL_L_LipLower1", "r": True, "t": True},
                        {"name": "FACIAL_L_LipLower2", "r": True, "t": True},
                        {"name": "FACIAL_L_LipLower3", "r": True, "t": True},
                        {"name": "FACIAL_R_LipLower1", "r": True, "t": True},
                        {"name": "FACIAL_R_LipLower2", "r": True, "t": True},
                        {"name": "FACIAL_R_LipLower3", "r": True, "t": True},
                        {"name": "FACIAL_L_LipLowerOuter1", "r": True, "t": True},
                        {"name": "FACIAL_L_LipLowerOuter2", "r": True, "t": True},
                        {"name": "FACIAL_L_LipLowerOuter3", "r": True, "t": True},
                        {"name": "FACIAL_R_LipLowerOuter1", "r": True, "t": True},
                        {"name": "FACIAL_R_LipLowerOuter2", "r": True, "t": True},
                        {"name": "FACIAL_R_LipLowerOuter3", "r": True, "t": True},
                        {"name": "FACIAL_R_LipUpper1", "r": True, "t": True},
                        {"name": "FACIAL_R_LipUpper2", "r": True, "t": True},
                        {"name": "FACIAL_R_LipUpper3", "r": True, "t": True},
                        {"name": "FACIAL_L_LipUpperOuter1", "r": True, "t": True},
                        {"name": "FACIAL_L_LipUpperOuter2", "r": True, "t": True},
                        {"name": "FACIAL_L_LipUpperOuter3", "r": True, "t": True},
                        {"name": "FACIAL_R_LipUpperOuter1", "r": True, "t": True},
                        {"name": "FACIAL_R_LipUpperOuter2", "r": True, "t": True},
                        {"name": "FACIAL_R_LipUpperOuter3", "r": True, "t": True},
                        {"name": "FACIAL_L_LipUpper1", "r": True, "t": True},
                        {"name": "FACIAL_L_LipUpper2", "r": True, "t": True},
                        {"name": "FACIAL_L_LipUpper3", "r": True, "t": True},
                        {"name": "FACIAL_C_LipUpper1", "r": True, "t": True},
                        {"name": "FACIAL_C_LipUpper2", "r": True, "t": True},
                        {"name": "FACIAL_C_LipUpper3", "r": True, "t": True},
                        {"name": "FACIAL_C_LipUpperSkin", "r": True, "t": True},
                        {"name": "FACIAL_L_LipUpperSkin", "r": True, "t": True},
                        {"name": "FACIAL_R_LipUpperSkin", "r": True, "t": True},
                        {
                            "name": "FACIAL_L_LipUpperOuterSkin",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_R_LipUpperOuterSkin",
                            "r": True,
                            "t": True,
                        },
                        {"name": "FACIAL_C_LipLowerSkin", "r": True, "t": True},
                        {"name": "FACIAL_L_LipLowerSkin", "r": True, "t": True},
                        {"name": "FACIAL_R_LipLowerSkin", "r": True, "t": True},
                        {
                            "name": "FACIAL_L_LipLowerOuterSkin",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_R_LipLowerOuterSkin",
                            "r": True,
                            "t": True,
                        },
                        {"name": "FACIAL_L_LipCorner1", "r": True, "t": True},
                        {"name": "FACIAL_L_LipCorner2", "r": True, "t": True},
                        {"name": "FACIAL_L_LipCorner3", "r": True, "t": True},
                        {"name": "FACIAL_R_LipCorner1", "r": True, "t": True},
                        {"name": "FACIAL_R_LipCorner2", "r": True, "t": True},
                        {"name": "FACIAL_R_LipCorner3", "r": True, "t": True},
                    ]
                },
                "bendingWeight": "0.0",
                "meshName": "headMatchPass2_mesh",
                "nIterations": "10",
                "name": "pass2_default",
                "paintConstraintSplitMap": "JO_11_pass2_default_1",
                "rotationRegularization": "0.5",
                "sculptMesh": "head_lod0_mesh",
                "startType": "1",
                "strainWeight": "0.0",
                "translationRegularization": "0.0",
            },
            {
                "jointOptions": {
                    "jointOption": [
                        {"name": "FACIAL_L_LipCorner1", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipCorner2", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipCorner3", "r": True, "t": True},
                        {"name": "FACIAL_L_LipCorner2", "r": True, "t": True},
                        {"name": "FACIAL_L_LipCorner3", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipCorner1", "r": True, "t": True},
                        {"name": "FACIAL_R_LipCorner1", "r": True, "t": True},
                        {"name": "FACIAL_R_LipCorner2", "r": True, "t": True},
                        {"name": "FACIAL_R_LipCorner3", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipCorner1", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipCorner2", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipCorner3", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper16", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper17", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper18", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper19", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper20", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper21", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper22", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper23", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper24", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper24", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper23", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper22", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper21", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper20", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper19", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper18", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper17", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper16", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper15", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper14", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper13", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper12", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper11", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper10", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper15", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper14", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper13", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper12", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper11", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper10", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper9", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper8", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper7", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper6", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper9", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper8", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper7", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper6", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper5", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper5", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper4", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper4", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper3", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper3", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper2", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper2", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipUpper1", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipUpper1", "r": True, "t": True},
                        {
                            "name": "FACIAL_L_12IPV_LipUpperOuterSkin2",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_L_12IPV_LipUpperOuterSkin1",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_R_12IPV_LipUpperOuterSkin1",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_R_12IPV_LipUpperOuterSkin2",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_R_12IPV_LipUpperSkin",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_L_12IPV_LipUpperSkin",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_C_12IPV_LipUpperSkin2",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_C_12IPV_LipUpperSkin1",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_C_12IPV_LipLowerSkin1",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_C_12IPV_LipLowerSkin2",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_L_12IPV_LipLowerSkin",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_R_12IPV_LipLowerSkin",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_L_12IPV_LipLowerOuterSkin1",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_R_12IPV_LipLowerOuterSkin1",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_L_12IPV_LipLowerOuterSkin2",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_R_12IPV_LipLowerOuterSkin2",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_L_12IPV_LipLowerOuterSkin3",
                            "r": True,
                            "t": True,
                        },
                        {
                            "name": "FACIAL_R_12IPV_LipLowerOuterSkin3",
                            "r": True,
                            "t": True,
                        },
                        {"name": "FACIAL_L_12IPV_LipLower1", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower1", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower2", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower2", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower3", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower3", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower4", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower4", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower5", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower5", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower6", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower7", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower8", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower9", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower10", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower11", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower12", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower13", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower14", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower15", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower6", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower7", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower8", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower9", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower10", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower11", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower12", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower13", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower14", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower15", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower16", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower17", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower18", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower19", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower20", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower21", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower22", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower23", "r": True, "t": True},
                        {"name": "FACIAL_L_12IPV_LipLower24", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower16", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower17", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower18", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower19", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower20", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower21", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower22", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower23", "r": True, "t": True},
                        {"name": "FACIAL_R_12IPV_LipLower24", "r": True, "t": True},
                    ]
                },
                "bendingWeight": "0.0",
                "meshName": "headMatchPass3_mesh",
                "nIterations": "10",
                "name": "pass3_default",
                "paintConstraintSplitMap": "JO_07_pass3_forBetterPass2_1",
                "rotationRegularization": "0.5",
                "sculptMesh": "head_lod0_mesh",
                "startType": "1",
                "strainWeight": "0.0",
                "translationRegularization": "0.0",
            },
        ]
    },
    "name": "JO_09_pass23_stickies",
}
