//Maya Preference 2019 (Release 1)
//
//

runTimeCommand
	-label ""
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-annotation "Reset_T"
	-category "Custom Scripts"
	-hotkeyCtx ""
	-commandLanguage "python"
	-command ("import maya.cmds as cmds \nobjs = cmds.ls(sl= True) \naxis = ['X','Y','Z'] \nfor obj in objs: \n    for i,j in enumerate(axis): \n        if not cmds.getAttr('{0}.translate{1}'.format(obj, j), lock= True): \n            if cmds.getAttr('{0}.translate{1}'.format(obj, j), keyable= True): \n                cmds.setAttr('{0}.translate{1}'.format(obj, j), 0) ")
	Reset_T;

runTimeCommand
	-label ""
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-annotation "Reset_R"
	-category "Custom Scripts"
	-hotkeyCtx ""
	-commandLanguage "python"
	-command ("import maya.cmds as cmds \nobjs = cmds.ls(sl= True) \naxis = ['X','Y','Z'] \nfor obj in objs: \n    for i,j in enumerate(axis): \n        if not cmds.getAttr('{0}.rotate{1}'.format(obj, j), lock= True): \n            if cmds.getAttr('{0}.rotate{1}'.format(obj, j), keyable= True): \n                cmds.setAttr('{0}.rotate{1}'.format(obj, j), 0) ")
	Reset_R;

runTimeCommand
	-label ""
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-annotation "Reset_S"
	-category "Custom Scripts"
	-hotkeyCtx ""
	-commandLanguage "python"
	-command ("import maya.cmds as cmds \nobjs = cmds.ls(sl= True) \naxis = ['X','Y','Z'] \nfor obj in objs: \n    for i,j in enumerate(axis): \n        if not cmds.getAttr('{0}.scale{1}'.format(obj, j), lock= True): \n            if cmds.getAttr('{0}.scale{1}'.format(obj, j), keyable= True): \n                cmds.setAttr('{0}.scale{1}'.format(obj, j), 1) ")
	Reset_S;

runTimeCommand
	-label ""
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-annotation ""
	-category "Custom Scripts"
	-hotkeyCtx ""
	-commandLanguage "python"
	-command ("#alloff_needTurnOn\n\nimport maya.cmds as mc\n\n#getPannel\ndef getPanel():\n    currentPannel = mc.getPanel(underPointer = True) \n    if currentPannel == None:\n        currentPannel = mc.getPanel(withFocus = True)\n    print(currentPannel)\n    return currentPannel\n    \n    \nmyPanel = getPanel()\n\n\nmc.modelEditor(myPanel, e=True, allObjects=False)\nmc.modelEditor(myPanel, e=True, imagePlane=True)\nmc.modelEditor(myPanel, e=True, polymeshes=True)\nmc.modelEditor(myPanel, e=True, nurbsCurves=True)\nmc.modelEditor(myPanel, e=True, pluginObjects=('gpuCacheDisplayFilter',True))")
	Show_Toggle;

