//Maya Preference 2019 (Release 1)
//
//

nameCommand
	-annotation "SelectHierarchyNameCommand"
	-sourceType "mel"
	-command ("SelectHierarchy")
	SelectHierarchyNameCommand;

nameCommand
	-annotation "CenterPivotNameCommand"
	-sourceType "mel"
	-command ("CenterPivot")
	CenterPivotNameCommand;

nameCommand
	-annotation "FreezeTransformationsNameCommand"
	-sourceType "mel"
	-command ("FreezeTransformations")
	FreezeTransformationsNameCommand;

nameCommand
	-annotation "UVSetEditorNameCommand"
	-sourceType "mel"
	-command ("UVSetEditor")
	UVSetEditorNameCommand;

nameCommand
	-annotation "TogglePolyUVsCreateShaderNameCommand"
	-sourceType "mel"
	-command ("TogglePolyUVsCreateShader")
	TogglePolyUVsCreateShaderNameCommand;

nameCommand
	-annotation "SetMeshGrabUVToolNameCommand"
	-sourceType "mel"
	-command ("SetMeshGrabUVTool")
	SetMeshGrabUVToolNameCommand;

nameCommand
	-annotation "GraphEditorNameCommand"
	-sourceType "mel"
	-command ("GraphEditor")
	GraphEditorNameCommand;

nameCommand
	-annotation "HotkeyPreferencesWindowNameCommand"
	-sourceType "mel"
	-command ("HotkeyPreferencesWindow")
	HotkeyPreferencesWindowNameCommand;

nameCommand
	-annotation "TextureViewWindowNameCommand"
	-sourceType "mel"
	-command ("TextureViewWindow")
	TextureViewWindowNameCommand;

nameCommand
	-annotation "HypergraphDGWindowNameCommand"
	-sourceType "mel"
	-command ("HypergraphDGWindow")
	HypergraphDGWindowNameCommand;

nameCommand
	-annotation "HypershadeWindowNameCommand"
	-sourceType "mel"
	-command ("HypershadeWindow")
	HypershadeWindowNameCommand;

nameCommand
	-annotation "SelectVertexMaskNameCommand"
	-sourceType "mel"
	-command ("SelectVertexMask")
	SelectVertexMaskNameCommand;

nameCommand
	-annotation "SelectEdgeMaskNameCommand"
	-sourceType "mel"
	-command ("SelectEdgeMask")
	SelectEdgeMaskNameCommand;

nameCommand
	-annotation "SelectFacetMaskNameCommand"
	-sourceType "mel"
	-command ("SelectFacetMask")
	SelectFacetMaskNameCommand;

nameCommand
	-annotation "SelectUVMaskNameCommand"
	-sourceType "mel"
	-command ("SelectUVMask")
	SelectUVMaskNameCommand;

nameCommand
	-annotation "dR_viewXrayTGLNameCommand"
	-sourceType "mel"
	-command ("dR_viewXrayTGL")
	dR_viewXrayTGLNameCommand;

nameCommand
	-annotation "dR_objectXrayTGLNameCommand"
	-sourceType "mel"
	-command ("dR_objectXrayTGL")
	dR_objectXrayTGLNameCommand;

nameCommand
	-annotation "ReferenceEditorNameCommand"
	-sourceType "mel"
	-command ("ReferenceEditor")
	ReferenceEditorNameCommand;

nameCommand
	-annotation "SmoothPolygonNameCommand"
	-sourceType "mel"
	-command ("SmoothPolygon")
	SmoothPolygonNameCommand;

nameCommand
	-annotation "CombinePolygonsNameCommand"
	-sourceType "mel"
	-command ("CombinePolygons")
	CombinePolygonsNameCommand;

nameCommand
	-annotation "SeparatePolygonNameCommand"
	-sourceType "mel"
	-command ("SeparatePolygon")
	SeparatePolygonNameCommand;

nameCommand
	-annotation "FrameAllNameCommand"
	-sourceType "mel"
	-command ("FrameAll")
	FrameAllNameCommand;

nameCommand
	-annotation "ReversePolygonNormalsNameCommand"
	-sourceType "mel"
	-command ("ReversePolygonNormals")
	ReversePolygonNormalsNameCommand;

nameCommand
	-annotation "ImportNameCommand"
	-sourceType "mel"
	-command ("Import")
	ImportNameCommand;

nameCommand
	-annotation "Reset_TNameCommand"
	-sourceType "mel"
	-command ("Reset_T")
	Reset_TNameCommand;

nameCommand
	-annotation "Reset_RNameCommand"
	-sourceType "mel"
	-command ("Reset_R")
	Reset_RNameCommand;

nameCommand
	-annotation "Reset_SNameCommand"
	-sourceType "mel"
	-command ("Reset_S")
	Reset_SNameCommand;

nameCommand
	-annotation "Show_ToggleNameCommand"
	-sourceType "mel"
	-command ("Show_Toggle")
	Show_ToggleNameCommand;

