//Maya Preference 2019 (Release 1)
//
//
windowPref -topLeftCorner 225 150 -widthHeight 250 400 -maximized false -parentMain true outlinerPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 700 400 -maximized false -parentMain true hyperGraphPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 660 400 -maximized false -parentMain true graphEditor1Window;
windowPref -topLeftCorner 250 200 -widthHeight 1400 400 -maximized false -parentMain true timeEditorPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 660 400 -maximized false -parentMain true dopeSheetPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 1040 600 -maximized false -parentMain true nodeEditorPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 660 400 -maximized false -parentMain true shapePanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 1040 600 -maximized false -parentMain true posePanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 660 400 -maximized false -parentMain true clipEditorPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 524 470 -maximized false -parentMain true devicePanel1Window;
windowPref -topLeftCorner 75 75 -widthHeight 1440 900 -maximized false -parentMain true hyperShadePanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 700 400 -maximized false -parentMain true dynPaintScriptedPanelWindow;
windowPref -topLeftCorner 250 200 -widthHeight 550 562 -maximized false -parentMain true blindDataEditor1Window;
windowPref -topLeftCorner 150 200 -widthHeight 1120 640 -maximized false -parentMain true polyTexturePlacementPanel1Window;
windowPref -topLeftCorner 235 230 -widthHeight 1430 710 -maximized false -parentMain true contentBrowserPanel1Window;
windowPref -topLeftCorner -9 69 -widthHeight 1280 1024 -maximized true -parentMain false MayaWindow;
windowPref -topLeftCorner 480 905 -widthHeight 450 320 -maximized false -parentMain true NewFeatureHighlightWnd;
windowPref -topLeftCorner 210 390 -widthHeight 958 658 -maximized false -parentMain true PreferencesWindow;
windowPref -topLeftCorner 341 493 -widthHeight 1427 700 -maximized false -parentMain true HotkeyEditor;
windowPref -topLeftCorner 480 905 -widthHeight 256 262 -maximized false -parentMain true uvSetEditor;
windowPref -topLeftCorner 480 905 -widthHeight 470 540 -maximized false -parentMain true shelfEditor;
windowPref -topLeftCorner 480 905 -widthHeight 450 411 -maximized false -parentMain true pluginManagerWindow;
