//Maya Preference 2023 (Release 1)
//
//

optionVar -version 3;

// RecentFiles
optionVar -cat "RecentFiles"
 -sa "RecentFilesList"
 -sva "RecentFilesList" "D:/Justin/MetahumanFacialCSVTest/HeadAdded/SKM_CH_Mem1_MVC.ma"
 -sva "RecentFilesList" "D:/Justin/MetahumanFacialCSVTest/HeadAddedAnim/SKM_CH_Mem1_MVC.ma"
 -sva "RecentFilesList" "D:/Justin/MetahumanFacialCSVTest/CH_CleanUp/SKM_CH_Mem3_MVC.ma"
 -sva "RecentFilesList" "D:/Justin/MetahumanFacialCSVTest/HeadAdded/SKM_CH_Mem3_MVC.ma"
 -sva "RecentFilesList" "D:/Justin/MetahumanFacialCSVTest/HeadAddedAnim/SKM_CH_Mem3_MVC.ma"
 -sva "RecentFilesList" "D:/Justin/MetahumanFacialCSVTest/CH_CleanUp/SKM_CH_Mem4_MVC.ma"
 -sva "RecentFilesList" "D:/Justin/MetahumanFacialCSVTest/HeadAdded/SKM_CH_Mem4_MVC.ma"
 -sva "RecentFilesList" "D:/Justin/MetahumanFacialCSVTest/HeadAddedAnim/SKM_CH_Mem4_MVC.ma"
 -sva "RecentFilesList" "D:/Justin/SD_Paperman/SD_Paperman_High_V3.fbx"
 -sva "RecentFilesList" "Z:/OWIS/3D/Rig/CH/Mem4/_Final/FBX/SKM_CH_Mem4_Head.fbx"
 -sa "RecentFilesTypeList"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "FBX"
 -sva "RecentFilesTypeList" "FBX"
 -sa "RecentProjectsList"
 -sva "RecentProjectsList" "D:/Justin/STB/Mem3"
 -sva "RecentProjectsList" "D:/Justin/STB/Mem4"
 -sva "RecentProjectsList" "D:/Justin/STB/Mem5"
 -sva "RecentProjectsList" "D:/Justin/CSB/Mem2"
 -sva "RecentProjectsList" "D:/Justin/CSB/Mem3"
 -sva "RecentProjectsList" "D:/Justin/CSB/Mem4"
 -sva "RecentProjectsList" "D:/Justin/CSB/Mem5"
 -sva "RecentProjectsList" "D:/Justin/CSB/Mem1"
 -sva "RecentProjectsList" "D:/Justin/MetahumanFacialCSVTest"
 -sva "RecentProjectsList" "D:/Justin/SD_Paperman"
 ;

