//Maya Preference 2023 (Release 1)
//
//

optionVar -version 3;

// RecentFiles
optionVar -cat "RecentFiles"
 -sa "RecentFilesList"
 -sva "RecentFilesList" "V:/VFX/FSH/shot/e101/e101_s012_0290/ani/wip/scenes/e101_s012_0290_ani_v001_w02.mb"
 -sva "RecentFilesList" "V:/VFX/FSH/shot/e101/e101_s012_0290/ani/wip/scenes/e101_s012_0290_ani_v001_w01.mb"
 -sva "RecentFilesList" "v:/vfx/fsh/shot/e101/e101_s012_0290/ani/wip/scenes/e101_s012_0290_ani_v001_w03.mb"
 -sva "RecentFilesList" "V:/VFX/FSH/shot/e101/e101_s012_0290/ani/wip/e101_s012_0290_ani_v002_w01.mb"
 -sva "RecentFilesList" "v:/vfx/fsh/shot/e101/e101_s012_0290/ani/wip/scenes/e101_s012_0290_ani_v002_w01.mb"
 -sva "RecentFilesList" "v:/vfx/fsh/shot/e101/e101_s012_0290/ani/wip/scenes/e101_s012_0290_ani_v002_w02.mb"
 -sva "RecentFilesList" "c:/vtmpfsh/shot/e101/e101_s012_0300/ani/pub/scenes/e101_s012_0300_ani_v003.mb"
 -sva "RecentFilesList" "c:/vtmpfsh/shot/e101/e101_s012_0300/ani/wip/scenes/e101_s012_0300_ani_v007_w02.mb"
 -sva "RecentFilesList" "v:/vfx/fsh/shot/e101/e101_s012_0290/ani/wip/scenes/e101_s012_0290_ani_v003_w01.mb"
 -sva "RecentFilesList" "v:/vfx/fsh/shot/e101/e101_s012_0290/ani/wip/scenes/e101_s012_0290_ani_v003_w02.mb"
 -sa "RecentFilesTypeList"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sa "RecentProjectsList"
 -sva "RecentProjectsList" "R:/VFX/FSH/shot/e101/e101_s002_0020/ani/wip"
 -sva "RecentProjectsList" "R:/VFX/FSH/shot/e104/e104_s033_0315/ani/wip"
 -sva "RecentProjectsList" "P:/VFX/GGJ_V/shot/e131/e131_s001_1210/ani/wip"
 -sva "RecentProjectsList" "V:/VFX/ggj_v/shot/e131/e131_s001_1210/ani/wip"
 -sva "RecentProjectsList" "V:/VFX/ggj_v/shot/e131/e131_s001_1270/ani/wip/scenes"
 -sva "RecentProjectsList" "V:/VFX/ggj_v/shot/e131/e131_s001_1270/ani/wip"
 -sva "RecentProjectsList" "V:\\VFX\\GGJ_V\\shot\\e131\\e131_s001_1220\\ani\\wip\\maya"
 -sva "RecentProjectsList" "V:/VFX/FSH/shot/e104/e104_s033_0315/ani/wip"
 -sva "RecentProjectsList" "V:/VFX/FSH/shot/e101/e101_s039_0070/ani/wip"
 -sva "RecentProjectsList" "V:/VFX/FSH/shot/e102/e102_s006_0115/ani/wip"
 ;

